### ISSUE TITLE
Data Driven testing from json file as examples in Scenario Outline

### ISSUE THREAD

**Issue by YenikeRaghuRam** [behave/behave#1009]
How to perform the DDT from json file as examples in Scenario Outline?

```json
{
    "positive_integer_range": {
        "start": 0,
        "end": 2,
        "value": 1
    },
    "negative_integer_range": {
        "start": -2,
        "end": 0,
        "value": -1
    },
    "positive_real_range": {
        "start": 0.0,
        "end": 1.0,
        "value": 0.5
    },
    "negative_real_range": {
        "start": -1.0,
        "end": 0.0,
        "value": -0.5
    }
}
```

**Comment by jenisys** [comment]
SHORT ANSWER:

* Write your feature files as TEMPLATE, like: `features/my_scenario_outline.feature.jinja`
* Render the TEMPLATE instances as `*.feature` files (with your favorite template engine)
* Run the feature files with `behave`

OTHERWISE:
You need to wait until reading the data file (as `*.json`) into an Examples table of the ScenarioOutline is supported. This requires a preprocessor step mechanism in `behave` and an extension-point that supports table-generator functions with tags, like:

```gherkin
Feature:
  ScenarioOutline:
     …

  @table_generator.from_file=my_data.json
  Examples:
     | start | end | value |
```
