### ISSUE TITLE
QUESTION: How to include python step files outside of main folder

### ISSUE THREAD

**Issue by restagner** [behave/behave#1023]
I'm new to Behave.

The architect of our framework has set aside a directory labeled **Base**.  Within that directory is another directory labeled **ApiCommon**. Inside of ApiCommon is a steps file labeled **SharedSteps.py**

Our project structure looks like

```
.
├── Base
    ├── ApiCommon
        ├── SharedSteps.py
├── playbook
    ├── components
    ├── environment.py
    ├── sample_api.feature
    └── steps
```

I'm using VS Code, and from the command line when I run `behave playbook/sample_api.feature`, Behave can't find the shared step we are attempting to use.

My environment.py file looks like
```
from Base.ApiCommon import SharedSteps as APISteps
from Base.WebCommon import SharedSteps as UISteps

def before_hook(context, feature):
    context.API_URL = 'https://ientqa.espn.com/playbook-resources'
```

Is this an issue with Behave?  What might I be missing here?

**Comment by jenisys** [comment]
Mmh, that is not an issue for `behave` if you do the things correctly.

* Most of your problems seem to be Python related (and you seem to be a Python novice)
* If you do not install your shared steps, Python needs to know where to look for it:

  - The two methods are alternatives (but can also be used together)
  - Use `export PYTHONPATH=$PWD` environment variable (on UNIX) or `set PYTHONPATH=%CD%` on Windows (assumption: Your current working directory is the `ROOT_DIR` directory of your directory tree.
  - In `playbook/environment.py` file, use the `HERE` idiom to automatically setup the Python search path:

```python
# — FILE: playbook/environment.py
from __future__ import absolute_import, print_function
import sys
import os.path

HERE = os.path.dirname(__file__)
ROOT_DIR = os.path.abspath(os.path.join(„../„ , HERE))   # HINT: Fix Github web editor quoting corrections.
print(„USE: ROOT_DIR=%s“ % ROOT_DIR)
sys.path.insert(0, ROOT_DIR)

… # MORE: Left out here.
```

* For a `step-library` (your shared steps): Add a file like `playbook/steps/use_steplib_api_common_shared_steps.py` Python file that contains: `import Base.ApiCommon.SharedSteps` to register your shared steps (as glue code).
* Your shared steps package directories are lacking the `__init__.py` files on each directory level to mark it as Python package for Python
* WRONG NAME: `before_hook` should be `before_feature` with the signature that you are using.

OTHERWISE:
* Your `Base/ApiCommon/SharedSteps.py` does not follow the Python naming conventions (PEP-0008; snake_case instead of CamelCase for Python packages/modules).
  The package/module should be named `base/api_common/shared_steps.py`.

HINT:
* Use [Discussions](https://github.com/behave/behave/discussions) instead of `Issues` for questions like this in the future. It is supported/provided by Github since approx. 1-2 years.

SEE ALSO:
* PEP-0008: Styleguide for Python Code: https://peps.python.org/pep-0008/
* [features/step.use_step_library.feature](https://github.com/behave/behave/blob/main/features/step.use_step_library.feature)

**Comment by restagner** [comment]
Thanks so much for the detailed feedback.  I'll work with what you've supplied to fix my issue.
