### ISSUE TITLE
Is it possible to execute tests with tags from different files?

### ISSUE THREAD

**Issue by andrew-clear** [behave/behave#1024]
I have two different `.feature` files.
`test1.feature`
```
@high
Feature − Payment Process Test 2
@creditpayment_test1
Scenario − Credit card transaction
   Given user is on credit card payment screen
   Then user should be able to complete credit card payment
@debitpayment_test1
Scenario − Debit card transaction
   Given user is on debit card payment screen
   Then user should be able to complete debit card payment
```
`test2.feature`
```
@high
Feature − Payment Process Test 2
@creditpayment_test2
Scenario − Credit card transaction
   Given user is on credit card payment screen
   Then user should be able to complete credit card payment
@debitpayment_test2
Scenario − Debit card transaction
   Given user is on debit card payment screen
   Then user should be able to complete debit card payment
```

I tried to execute the code:
`behave  --tags=debitpayment_test2,debitpayment_test1`
But for some reason, this is not working for me. Am I doing something wrong?
Do I need somehow to set the order of tags? Feature files in alphabetical order? If feature files are in alphabetical order, how can I set which `.feature` file will be run first?

**Comment by jenisys** [comment]
Let‘s sort things out:

* `behave` assumes a default path, normally `features/`, where it looks for feature files if you provide none on the command line. Try to provide the directory where your features are located or the feature files paths on command line to ensure that `behave` really find the feature files.
* Because you have not shown what occurs, I cannot exactly tell what you did wrong.

EXAMPLE:

```sh
# — HINT: I use the —dry-run option here to check what will get executed (without executing it)
$ behave —dry-run -f plain —tags=debitpayment_test2,debitpayment_test1 features/test1.feature features/test2.feature
… # INSPECT which scenarios are shown (steps have „untested“ status due to dry-run mode)

# — MABYBE TRY: As comparison: Without —tags option or with one tag
$ behave —dry-run -f plain  features/test1.feature features/test2.feature
$ behave —dry-run -f plain —tags=debitpayment_test1 features/test1.feature features/test2.feature
```

OTHERWISE:

* Tag ordering: Is not important because logical-or in tag-expressions are associative (as to be expected)
* Feature file ordering: If you rely that features are executed in a specific order, you are doing something wrong
* You can constrain the feature file order by providing the feature file paths on command line in the desired order
