### ISSUE TITLE
context.browser object is unable to access selenium features or methods as mentioned in the document.

### ISSUE THREAD

**Issue by Suresh8236** [behave/behave#1064]
```python
# -- FILE: features/environment.py
# CONTAINS: Browser fixture setup and teardown
from behave import fixture, use_fixture
from selenium.webdriver import Firefox

@fixture
def browser_firefox(context):
    # -- BEHAVE-FIXTURE: Similar to @contextlib.contextmanager
    context.browser = Firefox()
    yield context.browser
    # -- CLEANUP-FIXTURE PART:
    context.browser.quit()

def before_all(context):
    use_fixture(browser_firefox, context)
    # -- NOTE: CLEANUP-FIXTURE is called after after_all() hook.
```

In your step implementations you can use the context.browser object to access Selenium features. See the [Selenium docs](https://seleniumhq.github.io/selenium/docs/api/py/api.html) (remote.webdriver) for details. Example using [behave-django](https://pypi.org/project/behave-django):

```python
# -- FILE: features/steps/browser_steps.py
from behave import given, when, then

@when(u'I visit "{url}"')
def step_impl(context, url):
    context.browser.get(context.get_url(url))
```

The above code snippet is provided in the official https://behave.readthedocs.io/en/latest/practical_tips.html document.
But context.browser is unable to access selenium features or methods. 

In detail : After entering context.browser. (get method is not showing). We need to type to access that. Is there any way to access from auto suggestion apart from typing.

**Comment by jenisys** [comment]
I am not quite sure how `context.get_url()` in the step implementation above should work.
It requires that you have a specific `Context` class that supports it or that you inject this function as method into the behave `Context` class.

MAYBE, SHOULD BE: `context.browser.get_url(url)` (or this functionality is provided by `behave-django` somehow).

OTHERWISE: Check the basics
Try to create the `selenium.webdriver.Firefox()` in a Python shell.
If it works there (and you can use it), you should be able to use it in `behave`.

If the `selenium.webdriver.Firefox` class has changed, please provide a pull-request that corrects the example.

POSSIBLE PROBLEM: 
You have not installed the webdriver for selenium.

SEE ALSO: 
* https://www.selenium.dev/documentation/webdriver/getting_started/install_drivers/

**Comment by bittner** [comment]
Is this right, you use Behave to test a Django application of yours?

If that is true, please go through the [behave-django documentation](https://behave-django.readthedocs.io/en/latest/webbrowser.html) to set up Behave with Django. Don't mix setup instructions from the Behave and the Behave-Django documentation, let alone Selenium and Splinter—unless you want to tackle setup problems all by yourself.

The setup instructions in our documentation should give you a working example. If they don't please let us know.

**Comment by jenisys** [comment]
No reaction: Close it.
