### ISSUE TITLE
feature.status is Status.failed in before_scenario() hook while all my scenarios passed

### ISSUE THREAD

**Issue by darcyc-chen** [behave/behave#1068]
1. feature file:

```gherkin
Feature:my feature
  Scenario: test case1
    Then 5 is greater than 4

  Scenario: test case2
    Then 2 is greater than 1

  Scenario: test case2
    Then 3 is greater than 2
```

2. steps:

```python
from behave import *
@then('{num1:d} is greater than {num2:d}')
def step_impl(context, num1, num2):
    assert num1 > num2
```

3. enviroment.py

```python
def before_scenario(context, scenario):
    print("feature status is:{}".format(context.feature.status))

```

4. result:

```
feature status is:Status.untested
feature status is:Status.failed
feature status is:Status.failed
```

**Comment by darcyc-chen** [comment]
my user case is to skip rest scenarios if one  scenario failed  in one feature.

**Comment by jenisys** [comment]
I provided a feature-file to verify the observed behaviour (in the commit above).
It contains also an explanation of the observed behaviour and a proof-of-concept solution for your desired functionality.

**SEE ALSO:**
* [issue.features/issue1068.feature](https://github.com/behave/behave/blob/main/issue.features/issue1068.feature)

**NOTE:**
What you are trying to do, is normally avoided because scenario(s) in a feature file should be independent during a test run. Your desired functionality suggests that this not the case and you are experiencing correlated failures in the remaining scenarios of this feature (or the test execution is rather long and you want to avoid it after a scenario has failed).

**Comment by darcyc-chen** [comment]
> I provided a feature-file to verify the observed behaviour (in the commit above). It contains also an explanation of the observed behaviour and a proof-of-concept solution for your desired functionality.
> 
> **SEE ALSO:**
> 
> * [issue.features/issue1068.feature](https://github.com/behave/behave/blob/main/issue.features/issue1068.feature)
> 
> **NOTE:** What you are trying to do, is normally avoided because scenario(s) in a feature file should be independent during a test run. Your desired functionality suggests that this not the case and you are experiencing correlated failures in the remaining scenarios of this feature (or the test execution is rather long and you want to avoid it after a scenario has failed).

thanks, It works fine with your solution. 
BTW, you're right, some of my test execution is very long, I divide them into several scenarios to make them more human-readable. For these Features, I will add a tag named "skipIfHasFailure". And my final code would be:
```
if scenario.status == Status.untested and "skipIfHasFailure" in scenario.effective_tags:
        logger.info("SKIP-SCENARIO: %s" % scenario.name)
        scenario.skip()
```
thanks again.
