### ISSUE TITLE
Throwing HOOK-ERROR if triggered from CICD pipeline, same code works fine locally

### ISSUE THREAD

**Issue by baala-cg** [behave/behave#1069]
I am able to run a behave python code locally through IDE but the same code is not working when i trigger it through CICD pipeline.
I am facing issues as below when i trigger the code through CICD pipeline:
Please assist me here.. Thank you in advance..

**Console output:**
```
HOOK-ERROR in before_scenario: NoSectionError: No section: 'env details'
HOOK-ERROR in after_scenario: AttributeError: 'Context' object has no attribute 'driver'
  Failing scenarios:
features/example.feature:3 scenario_name
0 features passed, 1 failed, 0 skipped
0 scenarios passed, 1 failed, 0 skipped
0 steps passed, 0 failed, 0 skipped, 0 undefined, 3 untested
Took 0m0.000s
```

Please find my environment details below:

**Environment setup details:**
Selenium : 4.5.0
Python : 3.8
Behave : 1.2.6

**Comment by bittner** [comment]
> HOOK-ERROR in before_scenario: NoSectionError: No section: 'env details'
> HOOK-ERROR in after_scenario: AttributeError: 'Context' object has no attribute 'driver'

Without your source code it will be hard to help you. You should also describe how you run your tests locally and how your pipeline runs them. A [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) would be ideal.

**Comment by jenisys** [comment]
As @bittner has suggested, you should provide a minimal example that allows one to help you (mind reading is always difficult).

OTHERWISE:
* Try to think or explore what is different between your IDE use case and the CI/CD pipeline
* Try to run your code in a shell in your workspace (that is similar to CI/CD pipeline constraints, hopefully).
  If works there, you need to narrow down what the difference is between your workspace and the CI/CD environment.  If it does not work, it is easier to explore why it is not working. This is normally best if you can do that in your workspace. Because „debugging“ the CI/CD pipeline in the CI/CD pipeline is time-consuming and an anti-pattern.
* I assume that your are using the same Python version in your workspace and/or IDE and in the CI/CD pipeline. Check the versions of the installed packages with `pip freeze` in workspace and CI/CD and compare the results.
* Selenium needs to have the browser driver installed. Maybe that is missing in your CI/CD environment.

**Comment by jenisys** [comment]
@baala-cg 
You seem to have a problem with your `config.ini` file.
Either it does not exist (in the container filesystem) or it is empty or it does not contain the section it complains about.

The other problems look like correlated failures (web driver is not setup because of problem with config-file).

**Comment by bittner** [comment]
As Jens mentioned, your `config.ini` may not exist _in the container filesystem_. That it exists in your repository proves nothing, since you have a problem when your project runs in your CI/CD environment. Verify your setup when it runs there. If it is container-based the problem may be that.

It is likely that your problem has nothing to do with behave as such. Especially because it runs fine locally, as you state.

**Comment by bittner** [comment]
Same issue [on StackOverflow](https://stackoverflow.com/questions/74466094/python-behave-attributeerror-context-object-has-no-attribute-driver), with more source code.

I got emailed in private. (Don't do this again, please. Public projects are for public, voluntary support.)
