### ISSUE TITLE
Steps forcibly capture stdout/logging

### ISSUE THREAD

**Issue by tmarble** [behave/behave#1075]
Despite my efforts to turn off all capturing with `--no-logcapture --no-capture --no-capture-stderr` I am unable to get any output from steps. NOTE: I can get output from environmental functions (like `before_all`).

Is this expected?

**Comment by janoskut** [comment]
Yeah that's the fault of the pretty formatter, which is the default formatter (`--format=pretty`). The problem is being discussed once in a while here, and I find it quite a poor situation.

To get your output printed to the console, you'd have to use another formatter, e.g. `--format=plain`.

**Comment by jenisys** [comment]
The hooks in the environment-file are not captured.
You can capture logging by using the `capture` decorator from `behave.log_capture`.

Otherwise, the command-line options for capturing stdout, etc. or disabling capture, are working.
Either the steps that you are trying to use are not executed or …

* Try to run `behave -f plain …` to see from the file-location output that your intended steps are getting executed. 
* Try `behave —verbose …` that dumps part of the of the configuration including capture-related config parts. 
* Make a step that should output something fail, like with `assert False, „XFAIL_HERE“` after the output.

OTHERWISE: Pretty formatter related

* The pretty-formatter uses a two-phase mechanism. If writes the step before it is executed and overwrites after the step-result is known (with the correct coloring green/red).
* In this case, use logging and prevent it from being captured to observe the log-output independent of the test results.

SEE ALSO:

* [features/capture_stdout.feature](https://github.com/behave/behave/blob/main/features/capture_stdout.feature)
* …
