### ISSUE TITLE
Using Rich to write colored text to terminal from step definition not working

### ISSUE THREAD

**Issue by stenaksel** [behave/behave#1078]
In my stepDefinitions I have tried to use rich for writing out to terminal with color. And I experienced Behave is working differently when I run it with  --wip.
In a steps.py file add `from rich import print as rprint` and then in a step definition add `rprint('[italic red]Hello[/italic red] World!')`

Running Behave with --wip will show the red italic "Hello", but running without --wip will not...

I find this to be a bug...

**Comment by jenisys** [comment]
The `--wip` changes a number of internal configurations if this option is enabled.
For example, it disables the stdout-capture, etc.

Normally, output from steps is captured and only shown if the step fails.
Try running `behave --no-capture ...` and you should see printed output.

OTHERWISE:
* Provide and use your own formatter class that always shows captured-output.
