### ISSUE TITLE
Command Line Option for Generation Python Template Code?

### ISSUE THREAD

**Issue by htcml** [behave/behave#1085]
If I only put `*.feature`files under features folder but no `*.py` files provider in steps folder, when I run behave, it will generate a template python code at the end of the output. Does behave have an option to generate this template python code?

**Comment by jenisys** [comment]
I think you mean the text output with the undefined/missing steps at the end of the test run.
Normally, you copy this text from the terminal output and paste it into a steps-file.

`behave` contains a proof-of-concept code for a formatter that writes these missing step function implementations to an `output-file` (that can be the default steps implementation file in the steps directory).

SEE ALSO:
* [behave/contrib/formatter_missing_steps.py](https://github.com/behave/behave/blob/main/behave/contrib/formatter_missing_steps.py)

NOTES:
* Normally, you want to have control what you are doing.
* Often you need to edit and adapt the missing steps implementation code because you often use placeholders
* You can use multiple formatters, one would be the missing-steps formatter (and its `output-file` )

**Comment by bittner** [comment]
If anyone is interested to make this more prominent in the [related documentation](https://behave.readthedocs.io/en/stable/formatters.html) please feel free to open a PR! :eyes:
