### ISSUE TITLE
What are the best practices to store the Behave report in Mongo DB?

### ISSUE THREAD

**Issue by GNSubrahmanyam** [behave/behave#1088]
I will create my custom format to store the report in Mongo. What are the best practices for storing the Behave report in Mongo DB?

@jenisys  Can you share your thoughts on this?

**Comment by jenisys** [comment]
I am not quite sure what you are trying to achieve (and I am not a Mongo DB expert).
I assume that you want to store a test report of one behave test run as a JSON file in the Mongo DB !?!

First, you need to decide what the data model in the JSON file should be (the schema).
Candidates for a schema are the JUnitXML report output format (or the JSON formatter output) or allure reports.

NOTES:
* JUnitXML comes in various flavours (because not schema was initially defined and it was tweaked and extended afterwards by various parties)
* Behave JUnitXML file(s) currently contain the test run of one feature per JUnitXML file.
  But there are Python packages that make it easy to combine the feature JUnitXML files into one JUnitXML file for a test run.

SEE ALSO:
* JUnitXML schema(s): [behave/etc/junit.xml](https://github.com/behave/behave/tree/main/etc/junit.xml)
* https://github.com/allure-framework/allure2
* https://github.com/allure-framework/allure-python
