### ISSUE TITLE
How to use the variables defined in environment.py in the feature file？

### ISSUE THREAD

**Issue by Rexze001** [behave/behave#1101]
I am using behave to write API automation tests, and then use allure to generate reports. 
Now there is a requirement that I need to pass in parameters from the outside. So I used the -D parameter in the command line to pass parameters：
`behave --tags=@wss -D name=test -s --no-capture --no-skipped -f allure -o reports/allure-result`

And I defined a variable in environment.py to receive the parameter:
`context.name = context.config.userdata.get("name", "dev")`

How can I use this parameter in the feature file to make allure's report title more readable?
For example：
```
Feature: test001
  Scenario Outline: **(I want to use the variables here)**
    Given ...
    When ...
```

**Comment by jenisys** [comment]
What you are trying to achieve:

* Corresponds to the properties in a JUnit XML report
* MAYBE: Use Allure Environment information to pass that data along with the allure report.
   SEE: https://docs.qameta.io/allure-report/#_environment

Otherwise, what you are trying to achieve is not directly possible in `behave` (like you described above):

* Gherkin/feature-file must exist before runtime (meaning: before it is executed)
* ScenarioOutline is a template to generate Scenarios for each Example table row
* ScenarioOutline only supports Example table column-name(s) as template placeholders
* Your parameters (as userdata) are only known at runtime

POTENTIAL SOLUTIONS:

* HACK: Annotate/extend the Scenario title (as `scenario.name`) at runtime by using the runtime parameters
* Provide a scenario that dumps the relevant parameters (from: userdata) as informational part of the report
* Use build-script that generates the feature-files from a template by using the parameters
  before you execute the feature-file with behave
* Use Allure Environment
* …

**Comment by Rexze001** [comment]
Thank you, Jenisys. I tried using the scenario.name to define the scenario name. 
```
def before_scenario(context, scenario):
      scenario.name += "-- test name"
```
And it works in the Pycharm project. 
<img width="400" alt="image" src="https://user-images.githubusercontent.com/22924327/234230224-6415ade8-1df8-4e5a-a20d-c14bd786c7ac.png">

But it doesn't work in the allure report, the scenario name in the allure report is still the original name. 
<img width="806" alt="image" src="https://user-images.githubusercontent.com/22924327/234231063-95ab68d2-cacb-474c-957d-e5cf62dba20f.png">

@Jiff21 Do you have any idea about this?
