### ISSUE TITLE
When I call 'json.dumps()' in 'step_implementation.py', the result for 'json.dumps()' showed in cucumber report is without double quote which should be there..

### ISSUE THREAD

**Issue by StellaWang2016** [behave/behave#1107]
I was about the do some REST API testing based on behave and cucumber report. We put all of the payload parameters for put/patch menthod as separate files in some folder. We use 'json.load()' to read content from those json files, the variable in the result is with single quote, then when I call 'json.dumps()' try to change the single quote to double quote which is required by REST API put/patch method, the result for 'json.dumps()' is no quote at all, while that debug information is displayed in cucumber report. I also tried 'json.dumps()' outside behave framework and cucumber, the result is with a double quote. Any idea how to deal with this? Thanks a lot!

**Comment by jenisys** [comment]
I am not quite sure if this is a `behave` issue.
In addition, you need to provide:

* a simple example what you have done
* What you observed
* What you expect (instead of the observation)

NOTES:
* `behave` does not change the way how `json.dumps()` works
* Use a `print(json_output)` in your step implementation and run `behave —no-capture …` to see this output and inspect it
* May be an issue of the cucumber-report formatter (which is not part of `behave`; other repository)

**Comment by StellaWang2016** [comment]
Find other way to resolve my problem, this is not a blocker for me as of now, so close it.
