### ISSUE TITLE
all feature executed with arg scenario:line if paths come from config object

### ISSUE THREAD

**Issue by callejerog** [behave/behave#1110]
Hi, I want to use my own runner to load paths dynamically. If I do it, then I am not able anymore to select the scenario to execute passing the line as argument.

Demo project:
![image](https://github.com/behave/behave/assets/19282092/a0d44160-2748-41a9-86e1-34f7e4d2a538)

asf_runner.py:
```import os

from behave.runner import Runner


class AsfBehaveRunner(Runner):
    def __init__(self, config):
        config.paths = ["tests"]
        super().__init__(config)
```

run_behave.py
```
from behave.__main__ import Configuration, run_behave
import sys
import os

from asf_runner import AsfBehaveRunner


def main():
    config = Configuration()
    return run_behave(config, runner_class=AsfBehaveRunner)


if __name__ == "__main__":
    sys.exit(main())
```

dummy.py:
```
from behave import given

@given('nothing')
def dummy(context):
    pass
```

test.feaure:
```
Feature: Test feature

    @test
    Scenario: Test 1
        Given nothing

    @test
    Scenario: Test 2
        Given nothing
```

If I run:
```python3 run_behave.py test.feature:4 -k```
I got both test run.

if I comment the line 
```config.paths = ["tests"]``` 
and run:
```python3 run_behave.py tests/test.feature:4 -k```
Only scenario at line 4 is run.

Could you help me understanding why?

Thank you

**Comment by jenisys** [comment]
* You should not override `config.paths = …` in your `AsfBehaveRunner` class.
   REASON: That overrides the command-line args if you use any.
* In your case, you override the specific FileLocation that you provide on command-line

DESIGN HINT: 
The default paths are a functionality of the Configuration, but should not be a functionality of the Runner (in most cases).

OTHERWISE:
* `behave` has no command-line option `-k`
* Specify your runner class in `behave.ini` as default runner (since: behave v1.2.7.dev3 at least).
  NOTE: Then you can use `behave` together with your runner class.

SEE ALSO:
* [behave.ini](https://github.com/behave/behave/blob/main/behave.ini#L41) (config-file with info on default-runner)

**Comment by callejerog** [comment]
In your case, you override the specific FileLocation that you provide on command-line

Thank you!! Now I got it.

I want to define several folders where to load steps, fixtures and features from.
I am setting there paths to set the folders where you should search for features (I know it only at runtime).
How should I do it?
 
Thanks so much for your help :)

**Comment by callejerog** [comment]
PS for fixtures and steps I am ok, missing only features...

**Comment by callejerog** [comment]
FYI I solved by using this code:

'''
def setup_paths(self): 
        if not self.config.paths:
            self.config.paths = load_features_function()
        super().setup_paths()
'''

so that it works if you run tags (searches in all features dirs), or dry runs, and also works if you specify a path.

Thanks for your hints and your job in general.

Bye  

Giulio
