### ISSUE TITLE
behave erroring in pretty format in pyproject.toml

### ISSUE THREAD

**Issue by morning-sunn** [behave/behave#1116]
version: behave `1.2.7.dev3`

So I have this pyproject.toml section:

```toml
# -- FILE: pyproject.toml
[tool.behave]
paths = ["atumm/user/infra/features/token"]
format = "pretty"
```

and running behave, causes this lookup error, which splits pretty into characters and fails:

```bash
$ behave -v
Loading config defaults from "./pyproject.toml"
Using CONFIGURATION DEFAULTS:
             color: auto
    default_format: pretty
      default_tags: 
           dry_run: False
            format: pretty
              jobs: 1
             junit: False
       log_capture: True
logging_clear_handlers: True
    logging_filter: -suds
    logging_format: %(levelname)s:%(name)s:%(message)s
     logging_level: 20
   more_formatters: {}
          outfiles: ['p.output', 'r.output', 'e.output', 't.output', 't.output', 'y.output']
            runner: behave.runner:Runner
scenario_outline_annotation_schema: {name} -- @{row.id} {examples.name}
      show_skipped: True
     show_snippets: True
       show_source: True
      show_timings: True
             stage: None
    stderr_capture: True
    stdout_capture: True
     steps_catalog: False
           summary: True
          userdata: {}
usage: behave [options] [ [DIR|FILE|FILE:LINE] ]+
behave: error: BAD_FORMAT=p (problem: LookupError: 'p'), r (problem: LookupError: 'r'), e (problem: LookupError: 'e'), t (problem: LookupError: 't'), t (problem: LookupError: 't'), y (problem: LookupError: 'y')

```

Is there a stacktrace option, I am willing to look into it, and open a PR

**Comment by bittner** [comment]
Thanks for reporting the issue! :100: 

@jenisys will certainly step in and tell you about the options to get a stacktrace displayed, if any. In the meantime:

The problem seems to be that the string is evaluated as a sequence of characters. Hence, if you turn the value into a list of strings you will likely get this issue resolved. (Though, we should then discuss the naming of the configuration option, because the singular "`format`" in combination with a list of strings seems counterintuitive.)

- The problem is reported in the [configuration module](https://github.com/behave/behave/blob/v1.2.7.dev3/behave/configuration.py#L810-L816) at line 816.
- The TOML file is processed by the [`read_toml()` function](https://github.com/behave/behave/blob/v1.2.7.dev3/behave/configuration.py#L506-L550) starting at line 506 in that module.
- The [`select_bad_formats_with_errors()` method](https://github.com/behave/behave/blob/v1.2.7.dev3/behave/configuration.py#L844-L862), starting at line 844, identifies the "bad formats". It clearly loops over an iterable of `self.format`, which seems to be the configuration string "`pretty`" in your case.

Can you try out the same configuration with an INI-style format (i.e. place it in `tox.ini` or `behave.ini`) to see whether Behave expects a list in general, or it's actually a bug of the TOML implementation? That would be great. :+1:

**Comment by jenisys** [comment]
I need to look into.

BUT: 
You can specify multiple formatters.
In TOML, that means you should an array.
As @bittner has analyzed above, you have probably provided a string (as it is shown in your issue above).

TOML CONFIG (should be):
```toml
[tool.behave]
format = ["pretty"]
# WRONG: format = "pretty"

# HINT: Better use:
default_format = "pretty"
```

**Comment by jenisys** [comment]
INTEGRATED INTO: behave v1.2.7 (after v1.2.7.dev3 release tag)

* Improve diagnostics if wrong type is used for config-param

**Comment by jenisys** [comment]
SEE ALSO: For improved diagnostics on error
* [issue.features/issue1116.feature](https://github.com/behave/behave/blob/main/issue.features/issue1116.feature#L45)
