### ISSUE TITLE
Errors are swallowed when timeout parameter is used for @async_run_until_complete

### ISSUE THREAD

**Issue by GooDer** [behave/behave#1119]
When new async approach is used to write test steps, errors are swallowed and ignored when timeout parameter is used for annotation.

Example step to reproduce:

```python
@given("test")
@async_run_until_complete(timeout=1)
async def step_impl(context):
    raise Exception("test")
    await asyncio.sleep(1)
```
Python version 3.8.14
Behave version 1.2.6

**Comment by GooDer** [comment]
Seems to be already addressed in main https://github.com/behave/behave/blob/3ebf4010755d921873ae83599eba8b56b0006dae/behave/api/async_step.py#L142

**Comment by jenisys** [comment]
Can it be closed then ?

**Comment by GooDer** [comment]
Hi @jenisys, sorry for late response. Issue itself will be fixed in newer version but it still exists in 1.2.6.
Could it be fixed also in that version (or new hotfix version created) since this is quite dangerous bug.

If not it would be good to state it in documentation that this bug exists and everybody should be aware of it.

It happened that we got test which seems to be passing but it was silently failing and we didn't know that we had problem in production code.

**Comment by jenisys** [comment]
Install `behave v1.2.7.dev3` via pip from this repository.

SEE ALSO:

* https://behave.readthedocs.io/en/latest/install/

**Comment by bittner** [comment]
@jenisys Just as a side note: It may still a good idea to craft a release soon - and then keep releases coming and close to the tip of the code base.

For example, there was an [outage of GitHub yesterday](https://www.githubstatus.com/history) and I had pipeline jobs timing out, because _behave_ (and the latest of _behave-django_) couldn't be installed from source. GitHub as a fallback is okay, but it's painful if you depend hard on it.
