### ISSUE TITLE
Illegal hardware instruction python M1

### ISSUE THREAD

**Issue by Ymars1990** [behave/behave#1137]
python 3.9.1
computer: mac m1
macos version:11.5.1

when i run behave in terminal ,i get this 
please show me how to solve

**Comment by jenisys** [comment]
QUESTIONS:
* Did you use the the macOS python or another python version ?
* Did you use a virtual-environment or similar ?

SUGGESTION:
* Use `strace` or `dtrace` to diagnose which file is causing the problem

NOTES:
* `behave` does not depend on processor specific implementations (native Python package)
* Therefore, I assume that the problem is not caused by `behave` directly

**Comment by jenisys** [comment]
Try the following (to check if it helps):

```bash
$ pip uninstall behave
$ pip install —-non-binary :all: behave
# OR: pip install —-no-binary :all: git+https://github.com/behave/behave.git@v1.2.7.dev5
```

SEE ALSO:
* pip-install docs (point 12): https://pip.pypa.io/en/stable/cli/pip_install/

**Comment by jenisys** [comment]
NO REACTION, seems to be solved.
