### ISSUE TITLE
Why behave doesn't allow to define steps with duplicated descriptions?

### ISSUE THREAD

**Issue by ldynia** [behave/behave#1157]
#### Context

It looks like every step in behave must have a unique description.

```shell
  File "/usr/local/lib/python3.10/site-packages/behave/step_registry.py", line 58, in add_step_definition
    raise AmbiguousStep(message % (new_step, existing_step))
behave.step_registry.AmbiguousStep: @when('the city's weather forecast page is requested') has already been defined
```

#### Question

Why behave doesn't allow to define steps with duplicated descriptions?

**Comment by jenisys** [comment]
`behave` is preventing you from doing something wrong/stupid:

* If you have two steps with the same step description but different implementations, you are basically looking for trouble.
* If you have two steps with the same step description but the same implementation in two places, you have also done something wrong (unnecessary code duplication).

OTHERWISE:
* The matching of the steps is normally not as easy. Often, a step has one or more parameters that must be matched.
* It is up to you in your `step design` to ensure that steps are not ambiguous.

**Comment by ldynia** [comment]
Now I know. Thanks :)
