### ISSUE TITLE
ParseMatcher failing on steps with type annotations. 

### ISSUE THREAD

**Issue by omrischwarz** [behave/behave#1158]
Hi, all. Behave 1.2.6 right now sees these two steps as matching and raises AmbiguousStep: 

`Exception AmbiguousStep: @then('the SCADA finally reports that the supervisory controls communication status is {com_state:CommunicationState}') has already been defined in
  existing step @then('the SCADA reports that the supervisory controls communication status is {com_state:CommunicationState}') at features/steps/operational_states.py:615
Traceback (most recent call last):
`

Digging deeper I found that the culprit is the ParseMatcher check_match function: 

```
    def match(self, step):
        # -- PROTECT AGAINST: Type conversion errors (with ParseMatcher).
        try:
            result = self.check_match(step)
            print("RESULT",result)
        except Exception as e:  # pylint: disable=broad-except
            print("EEE",e)
            return MatchWithError(self.func, e)
```

The exception is 
```EXISTING <ParseMatcher: 'the SCADA that the supervisory controls communication status is {com_state:CommunicationState}'>
EEE Group names (e.g. (?P<name>) can cause failure, as they are not escaped properly: '\Athe System BMS reports that the supervisory controls communication status is (?P<com_state>(?i)ALIVE|(?i)SUSPICIOUS|(?i)DEAD|(?i)UNKNOWN)\Z'

```

My workaround right now is to remove type annotations, but it would be nice to be able to put them back .

**Comment by omrischwarz** [comment]
Type annotations are a bit too needful, so I tested changing the match() function to return None when it catches an exception. now the code passes.

**Comment by jenisys** [comment]
@omrischwarz 
* I provided a feature file to test your problem
* I cannot reproduce your AmbiguousStep exception w/ this feature file
* I would be astonished, if such a problem existed, because your step prefix text is completely different
* I assume the problem is somewhere else in your test environment or test code (for example your type-conversion function that you registered)

TESTED WITH:
* Current repo state (> `v1.2.7.dev5`)
* behave `v1.2.6`

SEE ALSO:
* [issue.features/issue1158.feature](https://github.com/behave/behave/blob/main/issue.features/issue1158.feature)

OTHERWISE:
* The core functionality of the `ParseMatcher` is provided by the [parse](https://github.com/r1chardj0n3s/parse) module.
* Any error in the generated regular expression, for example the mentioned missing escaping, would be located there.
