### ISSUE TITLE
Quotation marks in gherkin steps cause implementation mismatch

### ISSUE THREAD

**Issue by c92s** [behave/behave#1173]
When using the official Cucumber extension with the Python `behave` package, some steps with string variables are underlined and marked as "Undefined step". 

## Issue

A (string) parameter in Gherkin is passed in quotation marks as such: ``Given pass "foobar"``. The respective `behave` implementation is done as such:

```python
@step('pass "{string}"')
def step_impl(context, string):
    assert string == "bar", f"pass <{string}> is not <bar>"
```

The problem is, that the Cucumber extension cannot find the implementation, as the quotation marks "{string}" are interpreted as part of the keyword. When removing them in the decorator, the quotation marks from the Gherkin keyword are not escaped and passed as part of the string. Therefor, the following implementation leads to an error:

```python
@step("user {string}")
def step_impl(context, string):
    assert string == "foo", f"user <{string}> is not <foo>"    # --> Error Msg:  Assertion Failed: user <"foo"> is not <foo>
```

## Full Example:

```gherkin
Feature: Some new feature

  Scenario: Some Scenario
    Given user "foo"
    Given pass "bar"
```

```python
from behave import step


@step("user {string}")
def step_impl(context, string):
    assert string == "foo", f"user <{string}> is not <foo>"

@step('pass "{string}"')
def step_impl(context, string):
    assert string == "bar", f"pass <{string}> is not <bar>"
```

When running with `$ behave features/`

```bash
$ behave features/ 
Feature: Some new feature # features/test_step.feature:1

  Scenario: Some Scenario  # features/test_step.feature:3
    Given user "foo"       # features/steps/test_step.py:4 0.000s
      Assertion Failed: user <"foo"> is not <foo>

    Given pass "bar"       # None


Failing scenarios:
  features/test_step.feature:3  Some Scenario
```

## Possible solution(s)

I see two possibilities:
- Either the Cucumber vscode extension is able to detected decorators with parameters in quotation marks (e.g. ``@step('pass "{string}"'``)
- ``behave`` is able to strip quotation marks in the passed parameter, so decorators like this are possible ``@step("user {string}")``

I am not sure, however, which may be the ideal solution. Maybe you can give me some feedback.

**Comment by jenisys** [comment]
WRONG-REPO, you need to add this issue to the [cucumber/language-server](https://github.com/cucumber/language-server) repository.

* The python implementation(s) of the `behave` steps are the reference
* Whatever a step specifies must be used in feature-files and should be suggested by the language-server
* The testdata for the `cucumber-language-server` is currently lacking step-definitions with quoted-string parameters

NOTES:

* I am not quite sure how good the `cucumber-language-server` will serve you with `behave` (I mean if it officially supports it)
* It supports `*.py` files
* From my rudimentary explorations, I normally get `cucumber.undefined-step` for all/most of my steps. Therefore, `Go to Definition` does not work.
* Some steps are still suggested when you start typing in a Gherkin file. These suggestions seem to match other steps in other feature files.

OTHERWISE:
* Cucumber use `cucumber-expressions` mostly nowadays
* Behave use `parse/cfparse expressions` (marchers) normally in step definitions (which may be another problem)
