### ISSUE TITLE
Negative time execution bug possible with use of freeze_time

### ISSUE THREAD

**Issue by wojtekweg** [behave/behave#1180]
## Affected place

In `behave.reporter.summary.SummaryReporter.end` the following write:

```py
        # -- SHOW SUMMARY COUNTS:
        self.stream.write(format_summary("feature", self.feature_summary))
        self.stream.write(format_summary("scenario", self.scenario_summary))
        self.stream.write(format_summary("step", self.step_summary))
        timings = (int(self.duration / 60.0), self.duration % 60)
        self.stream.write('Took %dm%02.3fs\n' % timings)
```

Returns the following message on my CI and locally:
```
5 features passed, 0 failed, 0 skipped
20 scenarios passed, 0 failed, 0 skipped
96 steps passed, 0 failed, 0 skipped, 0 undefined
Took -311767m41.858s
CircleCI received exit code 0
```

## My setup

The command to run tests I use is ```env -S `cat .env.example` SERVICE_MODE=test poetry run python -m behave --stop --no-capture --no-color --format progress2 --tags=-skip features --junit --junit-directory=reports/behave```

I use following step for freezing time:
```py
@given('current time is fixed at "{isotime:ti}"')
def step_current_time(context, isotime):
    time_patcher = freeze_time(isotime, real_asyncio=True)
    time_patcher.start()
    context.patchers.append(time_patcher)
```
When I comment out this step body:

```py
@given('current time is fixed at "{isotime:ti}"')
def step_current_time(context, isotime):
    pass
```

The output is correct:

```
0 features passed, 1 failed, 0 skipped, 4 untested
5 scenarios passed, 1 failed, 0 skipped, 14 untested
32 steps passed, 1 failed, 5 skipped, 0 undefined, 58 untested
Took 0m0.788s
```

# Expected result

Running tests with freeze_time patcher doesn't influence the tests timings output.

**Comment by jenisys** [comment]
Well, what should I say:

* Works as designed
* you are currently in a area of **undefined behavior** (if you start fiddling with the main clock)

QUESTIONS:
* What `behave` version are you using ?
* I assume you use `freezegun` ? (This essential information is missing in your description)
* Have you restored the normal clock after the scenario ? (I assume that you did not do it; what are cleanup-functions good for anyway: `time_patcher.stop()` call should be missing AFAIK)

OBSERVATIONS (after quick analysis):
* `Summary.duration` is currently the sum of all `feature.duration`(s) that are executed
* If `Summary.duration` is negative, so are at least some `feature.duration`(s)
* Only because you did not observe it, the problem may be lurking elsewhere, too.

**Comment by jenisys** [comment]
ANALYSIS:
* You need to configure `freezegun` to ignore the `behave.model` module (see below).
* Adding a `cleanup-function` was not sufficient

```python
# -- SOLUTION:
# BEFORE: Using "freezegun.freeze_time()" in behave steps
import freezegun
freezegun.configure(extend_ignore_list=["behave.model"])
```

SEE:
* [issue.features/issue1180.feature](https://github.com/behave/behave/blob/main/issue.features/issue1180.feature)
* https://github.com/spulec/freezegun?tab=readme-ov-file#ignore-packages

**Comment by jenisys** [comment]
ANALYSIS:
* You need to configure `freezegun` to ignore one/some `behave` modules
* Adding a `cleanup-function` was not sufficient

```python
# -- SOLUTION:
# BEFORE: Using any "behave" steps with freezegun.freeze_time()
import freezegun
freezegun.configure(extend_ignore_list=["behave.model"])
```

SEE ALSO:
* [issue.features/issue1180.feature](https://github.com/behave/behave/blob/main/issue.features/issue1180.feature)
* https://github.com/spulec/freezegun?tab=readme-ov-file#ignore-packages
