### ISSUE TITLE
OpenSSL internal error: FATAL FIPS SELFTEST FAILURE

### ISSUE THREAD

**Issue by TonyJayHunt** [behave/behave#1197]
Run behave -f allure_behave.formatter:AllureFormatter -o reports/allure-results --tags=all
  behave -f allure_behave.formatter:AllureFormatter -o reports/allure-results --tags=all
  shell: /usr/bin/bash -e {0}
  env:
    TENANT_ID: ***
    CLIENT_ID: ***
    CLIENT_PWD: ***
    environment: dev
    test_type: Functional
    bulk: 
    tags: all
crypto/fips/fips.c:154: OpenSSL internal error: FATAL FIPS SELFTEST FAILURE
/home/github/_work/_temp/[2](https://github.com/Arch-StrategicAnalytics/UK_AbiFNOL_BDD/actions/runs/10700428874/job/29664260247#step:5:2)c73f6bc-0000-40f5-baeb-18b1fd9c3e71.sh: line 1:   266 Aborted                 (core dumped) behave -f allure_behave.formatter:AllureFormatter -o reports/allure-results --tags=all

I am seeing this error every time we run this in github actions using the latest redhat

**Comment by bittner** [comment]
I'm afraid this problem is not specific to Behave.

FIPS is some sort of security standard and (some) RedHat images run in FIPS mode, which causes issues when certain prerequisites are not met. Please, do some research on the Internet to understand how to fix the issue of your environment.

### References / Related

- [FIPS: custom python 3.9 application loading pymssql package crashes](https://access.redhat.com/solutions/7035895) (RedHat Knowledgebase)
- [Fatal FIPS Selftest Failures](https://www.suse.com/support/kb/doc/?id=000018558) (SuSE Knowledgebase)
- https://github.com/aws/aws-sam-cli/issues/4618
- https://github.com/pyinstaller/pyinstaller/issues/8273
- [FIPS](https://en.wikipedia.org/wiki/Federal_Information_Processing_Standards) (Wikipedia)

**Comment by bittner** [comment]
Closing this issue as off-topic. Feel free to reopen or comment.
