### ISSUE TITLE
Definition of default tags

### ISSUE THREAD

**Issue by brianpeiris** [behave/behave#301]
behave should support @skip tags over scenarios out of the box. It's inconvienient to have to specify a `--tags` option every time.

**Comment by s1ider** [comment]
Right now you can specify tags you want to skip automatically in file .behaverc, like:

    [behave]
    tags=-skip

**Comment by jenisys** [comment]
As @s1ider mentioned, there exists some support for a set of default tags by using behave's configuration file. I need to think about, if more is really needed.

NOTE:
My normal configuration sets ``--tags=-@xfail --tags=-@not_implemented`` rather often (by default), if no tags are provided, to exclude features/scenerios that are (currently) expected to fail or are not implemented yet (just prepared with some step specification from a brain storming session).

**Comment by jenisys** [comment]
Use the following example:

```ini
# -- FILE: behave.ini
[behave]
default_tags = -@skip -@not_implemented -@xfail
```

The suggested solution (using: tags in configfile) does not work because you cannot override default tags. This is often the problem with command-line options that use the append-action. You cannot distinguish if defaults (from a configfile) should be merged or overwritten.

**Comment by jenisys** [comment]
INTEGRATED INTO: behave-1.2.6.dev0
