### ISSUE TITLE
Dependencies for steps

### ISSUE THREAD

**Issue by tsouvarev** [behave/behave#304]
Hi, I wonder is there any way to specify dependencies for step?

Here is example: I have a test, that checks that payment runs as expected. Payment object requires User and Card objects to be in `context`. Card also requires User object.

What I do now is writing a Background steps like 
"There is partner in the system" (creates partner)
"There is card in the system" (creates card, requires partner)
"There is payment in the system" (creates payment, requires partner and card)

I tried to use `context.execute_steps` to reduce steps in Background just to 
"There is payment in the system"

But if I execute "There is partner in the system" in both card-creating and payment-creating steps, then this step will be executed twice, and voila, I have two partners.

Is there any API similar to gulp dependency system, that runs task once, even if it was specified a few times?

**Comment by jenisys** [comment]
If you have a "setup dependency", it is best to provide good examples how your steps should be used and apply "Design-by-Contract". If a step implementation requires that a context attribute exists, check this precondition with an assert statement. This will explain the user what he/she did wrong, when steps are used in the wrong order.

EXAMPLE:
```python
@given("there is a card in the system")
def step_card_in_the_system(context):
    assert context.partner, "REQUIRE: partner is provided/defined."
    # OR: dependency injection => Perform the necessary tasks (if that is better)
    ensure_partner_is_provided(context)  # Will inject partner, if it is not stored already in the context.
    ...
```

**Comment by tsouvarev** [comment]
Well, `assert` is useless for me because my problem is two and more runs of step, so partner becomes kind of *overdefined* rather than *undefined*. 
`ensure_partner_is_provided` solves the issue, but that's just wrapper, and I want to simply declare dependency with framework taking care of necessary wrappers.
Don't you think this would be handy?

**Comment by jenisys** [comment]
You have a problem with assumptions in steps which context attributes (or problem domain entities) should exist or are provided. This is a step implementation problem and your only looking at rather simple case. In the generic case, there are for example multiple steps that can create an entity (example: partner, …) because you may need additional information to create your entities.

Therefore, it is not one solution for this problem but many. This is the difference between tasks in a build-system and BDD tests. In addition, if you think it is better to use some kind of declarative style to automatically inject missing entities into the context, provide some decorators for it and apply them to your step definitions. Maybe others find  it useful, too.

**Comment by tsouvarev** [comment]
Ok, thank you for your time.

**Comment by tsouvarev** [comment]
Ok, thank you for your time.
