### ISSUE TITLE
Exception when trying to call steps in environment module

### ISSUE THREAD

**Issue by madazone** [behave/behave#306]
I tried to run steps during the before_all hook in the environment.py module but I get the following error

    raise ValueError('execute_steps() called outside of feature')
ValueError: execute_steps() called outside of feature

**Comment by jenisys** [comment]
Well, the exception already tells you what you are doing wrong. Steps are for features and the ``before_all()`` hook is for setup to your context/problem domain. You are not intended to run steps there. You should call your python functions from your python modules instead.

**Comment by PyDeq** [comment]
BTW @jenisys, can you please elaborate on "You should call your python functions from your python modules instead."? Which modules are you talking about? AFAIK, the feature (sub-)directories are not on ```PYTHONPATH``` and putting everything into ```environment.py``` does not sound very good...
Personally, I considered using ```execute_steps``` as I nice solution to the problem of unimportable step implementations.

**Comment by jenisys** [comment]
Sorry, because you have a hammer not every material is a nail (and yes you can also apply a hammer to screws). The environment is not intended for test (feature) setup with execute_steps. If you need a common preparation provide it as python code that can be used from your step implementation and your environment file.

**Comment by PyDeq** [comment]
OK, I can live with that. Can you please advice me where to put such Python code so that I can import it from both the environment file and the step implementations? Is that documented somewhere?

**Comment by jenisys** [comment]
The easiest way (in a development project) is to put the python packages on the same level like the feature directory. This leads to the following directory structure:

```
+-- my_package/
|    +-- __init__.py
|    +-- alice.py
+-- features/
     +-- steps/
     +-- *.feature
```

You may need to set the environment variable "PYTHONPATH=." assuming you run the behave tests from the project-root directory, like "behave features/". From the environment-file or steps file you can import your functionality, like:

```py
from my_package.alice import setup_everything
…
```

**Comment by PyDeq** [comment]
Hm, I hoped for a solution without a need to modify PYTHONPATH. I hoped that behave already has preconfigured a path where it looks for such files.
Given the example above with the REST API only, it would mean that I would have to include a code that calls the REST API into the package. This is not desirable. But since I need to modify PYTHONPATH anyway, I can probably make a separate "test" package for this code...
Also, for the other contributors, I would have to make some instructions about the need to set appropriate PYTHONPATH...
For me, it still sounds like a missing feature in behave that it is not allow implicit code sharing between step implementations and/or the environment file.
If I could understand why is environment file considered a bad material for a hammer usage, maybe I could live easier with this unnecessary hassle. I don't see what is the big difference between ```before_all``` and e.g. ```before_feature``` that makes it possible to call ```excecute_steps``` in one but not in the other one.

**Comment by jenisys** [comment]
Well, I disgree. Setup of python search-path is standard Python. Every Python developer should know that. Therefore, there is no need to provide a solution for this in behave.

If you think that you really need "execute_steps()" functionality in the environment-file, provide your own *Executor* that does just that. But that is not a clean solution (in my opinion).

**Comment by rholy** [comment]
Well, I (I'm using my work account now but it's still me :D ) expected that behave should work the same as the other test runners (e.g. nose, py.test etc.). They apparently allow me to run just e.g. "nosetests tests/" and it automatically put the current working directory on PYTHONPATH so that the tests can ```import my_package.alice``` as well as e.g. ```import tests.support``` (if the "tests" directory contains a "support.py" file) without any need to modify PYTHONPATH.
Anyway, I tried to run behave on the similar directory structure and it works too without any PYTHONPATH modification (well, I needed to add "__init__.py" files into the subdirectories). Also just ```import support``` (note the missing ```tests.```) in both the environment file and the steps implementation file worked. But given the discussion above I assume that this is unexpected/undocumented/unsupported.

But the more I think about it the more I agree with you that explicitly setting the correct PYTHONPATH is the best and that it may lead to unexpected behaviour if behave would do that implicitly. So, I apologize for saying that it is an unnecessary hassle.

So now, I'm thinking about the best place... "./tests/*.py", "./features/*.py", "./features/support/*.py"... Have seen some of these variants in practice?

Can you please elaborate on why do you think that using ```execute_steps``` in ```before_all``` is not a clean solution? I still did not get it.
