### ISSUE TITLE
setuptools_behave.py Subprocess call failing

### ISSUE THREAD

**Issue by kenr** [behave/behave#310]
I'm not able to run the behave tests from setup.py and I think it is because of a bug in the behave_test.behave method;

The call return subprocess.call([sys.executable, behave] + shlex.split(cmd_options)) tries to call python.exe subprocess (and the rest of the arguments). Should it not be python -m behave (and the rest of the arguments) ?

**Comment by jenisys** [comment]
Which platform (Windows, Linux, …) and which python version are you using ?

**Comment by jenisys** [comment]
I will fix it, but:
If the installed Python scripts are not found, you have setup the the Python installation incorrectly. Because other installed Python scripts will also not be found, like pip, …

For example on Windows, your search-path for Python should look like:
``PATH="C:\Python27;C:\Python27\Scripts;…"``

On Windows, the search is not automatically set up like that by the Python installer. Therefore, the user should normally correct it in its environment setup. Similar problems may exist on MACOSX if you use an own installation (not the system installation).

**Comment by jenisys** [comment]
INTEGRATED INTO: behave-1.2.6.dev0

**Comment by kenr** [comment]
Sorry for the late reply. Thank you for looking into and fixing the issue. I'm on Windows with Python version 2.7.6.

**Comment by memee** [comment]
Problem is line `behave = os.path.join("bin", "behave")` - it won't exist.
Working directory is the place where you call setup.py.

**Comment by jenisys** [comment]
@memee 
Why should that be the problem? 
If that does not exists, it is assumed that behave is in the python search path (or installed).

**Comment by memee** [comment]
Ok, steps to reproduce
```
$ mkvirtualenv -p /usr/local/bin/python3.4 test_behave
$ pip install pyramid
$ pcreate -s starter .
$ pip install behave
$ python setup.py behave_test
/Users/macio/.virtualenvs/test_behave/bin/python: can't open file 'behave': [Errno 2] No such file or directory
FAILED
```

It checks for relative 'bin/behave' in working directory, doesn't it?
```
$ python -c 'import os; print(os.path.exists(os.path.join("bin", "behave")))'
False
```
But behave is installed
```
which behave
/Users/macio/.virtualenvs/test_behave/bin/behave
```

**Comment by jenisys** [comment]
@memee
You seem to be talking about behave-1.2.5. As you can see this problem is already fixed in the Git repository.
