### ISSUE TITLE
Active Tags fail with ScenarioOutline

### ISSUE THREAD

**Issue by BRevzin** [behave/behave#384]
If I try to use ActiveTags with a ScenarioOutline:

    @use.with_tag=value
    ScenarioOutline: Hi
        Given test <name>

    Examples:
      | name |
      | Bob  |

the tag will get mangled into `use.with_tagvalue` by the time we get to `before_scenario()`, which mean that the ActiveTagMatcher won't even interpret it as something to be matched against.

I think the issue is in `Tag.make_name`, which currently restricts the allowed characters to `u'._-'`. Adding the `=` sign should fix it. Although why `make_name()` at all?

**Comment by jenisys** [comment]
It is not sensible to allow everything in a template (what the ScenerioOutline basically is). Otherwise, the template becomes a security problem.

WORKAROUND (until the problem is fixed):
Adapt the ``tag_schema`` and ``value_separator`` parameters for the ``ActiveTagMatcher`` object to comply with the currently implemented convention in ``ScenarioOutline``. This allows to define your own naming conventions for active tags.

```python
# -- file:features/environment.py
from behave.tag_matcher import ActiveTagMatcher
...
class MyActiveTagMatcher(ActiveTagMatcher):
    tag_schema = ...       # TODO: Left as exercise ;-)
    value_separator = "_"  # For example

active_tag_matcher = MyActiveTagMatcher(active_tag_value_provider)
```

**Comment by BRevzin** [comment]
What security problem? I'm trying to run my own tests for my own code.

**Comment by jenisys** [comment]
INTEGRATED INTO: behave-1.2.6.dev0
