### ISSUE TITLE
Support async/@asyncio.coroutine steps

### ISSUE THREAD

**Issue by dcarp** [behave/behave#409]
It should be possible to write behave steps that are using the `asyncio` module.

Example:
```python
@given("this condition")
async def setup_condition(context):
    ...
```
or with python 3.4.x:
```python
@given("this condition")
@asyncio.coroutine
def setup_condition(context):
    ...
```

**Comment by jenisys** [comment]
Why should that be useful ? 
Provide a real, compelling use case (but simple).

Steps are the "API", executed by the behave test runner (and its model elements).
They are executed in a sequence, but your step implementation can make use of async features.

**Comment by dcarp** [comment]
Short real example without `async`/`@asyncio.coroutine`:

```Python
@then('the received message is "{message}"')
def check_received_message(context, message):
    loop = asyncio.get_event_loop()

    async def do_test(context):
        assert await context.client.receive() == message

    loop.run_until_complete(do_test(context))
```

with `async`/`@asyncio.coroutine`:

```Python
@then('the received message is "{message}"')
async def check_received_message(context, message):
    assert await context.client.receive() == message
```

**Comment by jenisys** [comment]
The step writer has all the knowledge what needs to be done:

* knows which async eventloop is needed
* knows if a step should be executed with completion semantics or not
  (async-run-to-completion or async-dispatch)

The async setup/teardown should be simplified in the step implementation code (because it will repeat itself many times):

* provide ContextManager implementations for the common case
* provide a step-decorator that implements the ContextManager call

EXAMPLE:
```python
from behave import step
from xxx.step_decorators import with_async_event_loop

@step('an async step is executed with param "{param}"')
@with_async_event_loop
async def async_step_with_param(context, param):
    """Should be equivalent to:

    .. code-block:: python

        # -- EQUIVALENT-CODE: When step is called
        async def async_step_impl(context, param):
            ...

        loop = asyncio.get_event_loop()
        try:
            loop.run_until_complete(async_step_with_param(context, param)
        finally:
            loop.close()
    """
```

NOTE: 
The multi-step use case should also be solved by providing additional decorators:
* using the an async eventloop for multiple steps (simple: store it in the context)
* use async-dispatch instead of async-run-to-completion semantics on a step
* processing a future result in one of the next steps

SUMMARY:
If you are interested (or need such a solution), you should explore the exact functionality what is needed to work with coroutines as step implementation. All aspect and their potential variation-points/extension-points (basically what is needed for a generic solution) should be covered. The required functionality should be provided as (step-)decorators or ContextManagers (used inside a step implementation).

When a proof-of-concept exists, it can be deciced:
* if this should be integrated into behave (as standard solution)
* should be provided as behave support-package (might be easier to evolve if needed)

**Comment by jenisys** [comment]
INTEGRATED INTO: behave-1.2.6.dev0

**Comment by dcarp** [comment]
wow, that's awesome, thanks!

**Comment by jenisys** [comment]
:smile:
