### ISSUE TITLE
How to manage slow and fast datasets?

### ISSUE THREAD

**Issue by gregsaun** [behave/behave#410]
First of all, thanks for how your are developing Behave, it's a real pleasure to use it :)

I have an application that can takes several minutes/hours/days to process some datasets. This means I can't do a processing at each scenario.

To solve this, I have one feature that describe how the process should be done for few small datasets (1 to 5 min of processing time per datasets). And I have several other features that describe how the application works. Most of these features will use the results of the previously processed datasets. So, I first run the feature to process those small datasets and then run all others features. I do this several times a day (at each new build coming from the dev team). Note that dev team have also their own unit tests.

Now I'd like to write more scenarios that will need bigger datasets. Some of these new scenarios will be exactly the same as the current one (that are using small datasets) but with different expected results. These new scenarios will be executed during the night (or few times a week).

I thought I could use Scenario Outline and assign a tag for each Examples but it's not yet possible. So I tried [run-examples-group-via-select-by-name](http://pythonhosted.org/behave/new_and_noteworthy_v1.2.5.html#run-examples-group-via-select-by-name) and I came close to something similar than using tags on Examples. But I have these problems:
- it's a bit difficult to read
- I can't find a way to execute at the same time scenarios tagged as "slow" and scenarios with slow examples
- I'm not 100% sure it's the good approach to have

Do you have some advice to help me?

**Comment by jenisys** [comment]
Your problem is normally addressed through test suite organisation. You normally distinguish between:

* fast test (that are executed rather fast)
* slow tests (that take considerable more time)
* glacial tests (that take very long to run)

What exactly fast, slow and glacial means for you (how much is fast or slow...), depends of your use case. Therefore, you have 2-3 categories of test suites to run.

You have the following possibilities to make it simple to run these different test suite categories:

* Use the file system organisation (different directories or files) to split up the tests by fast/slow categories
* Use tags (@slow, @glacial) on Features, Scenarios, Scenario Outline or Scenario Outline Examples
  and disable @slow and @glacial during the "fast" test suite runs
* Use feature_listfiles (AT-Files), like: ``behave @slow_tests.txt`` that contains a list of features files (or file-patterns) or feature-locations (like: features/alice.feature:42, with 42 as line-number)

NOTES:
* You often use tags (@slow, ...) to solve your kind of problem
* Tags on Example tables in a Scenario Outline is only available in the Github repository

SEE ALSO:
* [features/scenario_outline.tagged_examples.feature](https://github.com/behave/behave/blob/master/features/scenario_outline.tagged_examples.feature)
* [docs/new_and_noteworthy_v1.2.6.rst](https://github.com/behave/behave/blob/master/docs/new_and_noteworthy_v1.2.6.rst)

**Comment by jenisys** [comment]
If need to wait for a official release for the Examples-with-tags support, split up the Scenario Outline with 2 Examples tables into 2 Scenario Outlines, each with only one Examples table (note: copy+paste, but a pragmatic approach and it is only text ;-)).

**Comment by gregsaun** [comment]
Thank you for your help, I tried the release from Github and it works fine with tags in Scenario Outline Examples, looking forward to the official 1.2.6 release. I'll use tags then, it's more aligned with BDD concepts and this will avoid repeating Scenarios in different test suites.
