### ISSUE TITLE
Support multiple active-tags with same category

### ISSUE THREAD

**Issue by Kani999** [behave/behave#411]
Hi, i would like to know how to use multiple active tags.
For example

@use.with_permission=admin
@use.with_permission=super_user
Scenario: Accept Cookies
    When something what can do admin and super_user only
    Then any of mentioned permmision doesnt work

If i use only one tag @use.with_permission everything works fine, but, when I try to use multiple active tags for one scenario, it doesnt work,.

**Comment by jenisys** [comment]
The active-tags functionality is specified in [features/tags.active_tags.feature](https://github.com/behave/behave/blob/master/features/tags.active_tags.feature),
If you use multiple active-tags, the logical expression uses and-logic, like:

```
enabled = enabled(active-tag1) and enabled(active-tag1) and ...
```

The currently implementation allows only one active-tag per category (for your use case)
and it does not merge values for the same category forms a list of allowed values.
But this is easily changeable by you, because the complete logic is in the extensible part of the overall test-runner. 

Provide a reasonable extension of the ``ActiveTagMatcher`` class that improves its behaviour (and covers all cases) and submit it as pull-request or implemented your own ``ActiveTagMatcher`` class.

WORKAROUND: 
As any good access control system can tell you, work with user-roles and not users (like Highlander: "there can be only one") :wink:.

**Comment by jenisys** [comment]
INTEGRATED INTO: behave-1.2.6.dev0
