### ISSUE TITLE
Expected errors step

### ISSUE THREAD

**Issue by yucer** [behave/behave#422]
Normally the code under test raise exceptions when validating the inputs.

What happen the case we have already many steps implementations for testing the normal functions and we want to test the validations ?

One solution is to call the functions of the implementations using try catch.

How can we implement a general step for validating the "expected error". I mean something like:

`and the next test step will fail..  `

**Comment by jenisys** [comment]
Well, look what your favourite unites framework would do in such a case. You should catch the expected exception (and any other to check for wrong exception). When an unexpected exception is raised or no exception is raised, raise an AssertionError or use an ``assert False, "..." `` statement.

You have more control when you try to use a nested step as text section. Now you are in control (instead of working against the test framework).

EXAMPLE:
```gherkin
    ...
    and the following step will fail:
       """
       Given the following step fails
       """
```

```python
# -- FILE: features/steps/my_steps.py
from behave import step

@step(u'the following step will fail')
def step_should_fail(context)
    assert context.text, "REQUIRE: text, that contains the step to fail"
    nested_step_fails = False
    try:
        context.execute_steps(context.text)
    exception AssertionError:
        nested_step_failed = True       
    except Exception:
        nested_step_failed = True
    assert nested_step_failed, "OOPS: Nested step did not fail."
```

Otherwise, if you do not want to use nested steps, you would need to perform the validation in the ``after_step()`` or ``after_scenario()`` hook, but I would not recommend that (SMELLS-BAD in my opinion).

**Comment by yucer** [comment]
**Good idea!**

**First option**:  Unfortunately the nested step doesn't redirect very good the inner exceptions messages when they have unicode characters ( #424 ). The fact is that I can not change those messages because they come from the system I'm testing.

**Second option**:  How can I check the step results inside the "after_" hooks ?

**Comment by jenisys** [comment]
Question 1: Answered in #424.
Question 2: Use ``step.status`` or ``scenario.status`` or ...

**Comment by yucer** [comment]
Sorry for the late feedback.

Thank you very much.
