### ISSUE TITLE
Provide charset explicitly to ``open``

### ISSUE THREAD

**Issue by throwable-one** [behave/behave#425]
There is the following code in its ``runner.py``
``

    with open(filename) as f:
        # -- FIX issue #80: exec(f.read(), globals, locals)
        # try:
        filename2 = os.path.relpath(filename, os.getcwd())
       code = compile(f.read(), filename2, 'exec')
``

As you can see, no charset is provided to open. According to its documentation, ``locale.getpreferredencoding`` is used for such cases.

But on Windows this function always return one-byte charset (so called "charset for non-unicode programs"). It is Windows-1252 for latin, Windows-1251 for Cyrillic etc.

So,UTF-8 py file is always broken.

As result, you can not use non-ascii characters in step definition files on Windows.

**Comment by jenisys** [comment]
Should be fixed in behave-1.2.6.dev0. Therefore, try the HEAD of the repository.
The new implementation should detect encoding specifications in your python file or the BOM as far as I know (by opening the file in binary mode).

But note you have control over the encoding of your python file and not the OS.
In my experience (and that of others), files with UTF-8 encoding cause the least problems with Python unicode.

**Comment by jenisys** [comment]
No feedback. Therefore, close it.

**Comment by throwable-one** [comment]
@jenisys sorry I did not answer you. Yes, it works now. Thank you. Do you have plans to release new version?

**Comment by jenisys** [comment]
@throwable-one 
I work on it, but I still need to fix some issues (partly Unicode problems).
