### ISSUE TITLE
Wizard populate suggest

### ISSUE THREAD

**Issue by vit1251** [behave/behave#434]
Nowadays it becomes more and more web applications of high complexity containing wizard for web forms, but it create question "how to specify values for the wizards forms?"

```
Given wizard form tab "1" specify params
     |  Name        | Value      |
     | key11         | value11  |
And wizard form tab "2" specify params
    | Name | Value |
     | key21         | value21  |
...
And wizard form tab "999" specify params
```

We can see that lost atomic in each action "And" split one operation. It increase couple and logic in one section.

Could you suggest how to more complex resolve this problem with BDD?

**Comment by vit1251** [comment]
I receive advise to start use materialize paths in values like 
```
Given wizard with params
 | Name           | Value     |
 | step1.key11 | value 11 |
 | step2.key21 | value 21 |
```
Do you have another solutions?

**Comment by aisbaa** [comment]
Hi, that's interesting problem you have . I have a feeling that wizard underneath is form, in that case https://github.com/ggozad/behaving might have solved your issue.

**Comment by jenisys** [comment]
@vit1251 In general the first example is a bad BDD, something that you should avoid because it describes the "user interface" (UI) and "how something is implemented". Instead, you should describe the "what should be provided", meaning the data model and product needs (its "intentions"). When you use the first solution (the "how"), your feature files and scenarios are brittle. They need to be adapted every time you change the "system under test" (SUT) or the test automation layer that uses the SUT. And that can be a lot of work. In the second case, your feature files are far more robust and the underlying implementation layers may change independently.

Therefore, example 2 looks better but are these parameters really the important parameters (and not incidental data that your current implementation needs). @aisbaa suggested "Personas" in ``behaving`` (I think). That is an approach how you can hide the incidental data from the feature files. 

Two days ago, Jenny Martin suggested something similar with [Data Personas](https://jennyjmar.com/2016/04/15/data-personas/) at the [CukesUp! 2016 conference](https://skillsmatter.com/conferences/7606-cukeup-2016) in London. Data Personas should be an even better fit for your use case.
