### ISSUE TITLE
Ambiguous Step definitions

### ISSUE THREAD

**Issue by kowalcj0** [behave/behave#435]
I don't understand why behave treats some of my step definitions as ambiguous.

Here are the dummy definitions depicting the issue:
```python
@given(u'a resource with "{field_1} {operator_1} {value_1}" in "{property_1}"')
def step_impl(context, **kwargs):
    pass

@given(u'a resource with "{field_1} {operator_1} {value_1}" in "{property_1}" and "{field_2} {operator_2} {value_2}" in "{property_2}"')
def step_impl(context, **kwargs):
    pass

@given(u'a resource with "{field_1} {operator_1} {value_1}" in "{property_1}" and "{field_2} {operator_2} {value_2}" in "{property_2}" and "{field_3} {operator_3} {value_3}" in "{property_3}"')
def step_impl(context, **kwargs):
    pass
```

I've created a repo with that you can use to reproduce this behaviour.
https://github.com/kowalcj0/ambiguous_steps_in_behave
If you run behave then it will always fail with **raise AmbiguousStep(message % (new_step, existing_step))**

I know that those step definitions are very similar, but spaces and double quotes should be treated as clear and explicit delimiters between the consequent parameters.
What should I do to get this working properly?

**Comment by jenisys** [comment]
WORK-AROUND: Reverse the order of the steps (start with most-complex to most-simple), then it works.
NOTE: This is a common recipe to avoid step ambiguity.

```shell
$ behave -f progress3
Ambiguous step definitions    # features/ambiguous.feature
  Test Ambiguous step definitions  ...

1 feature passed, 0 failed, 0 skipped
1 scenario passed, 0 failed, 0 skipped
3 steps passed, 0 failed, 0 skipped, 0 undefined
Took 0m0.000s
# -- VERIFY: Use "behave -f pretty" to check that behave is using the correct steps.
```

I will look into it.

**Comment by kowalcj0** [comment]
Thank you @jenisys I'll give it a go when I get to work :)

**Comment by kowalcj0** [comment]
Reordering the step definitions worked like a charm. Thank you @jenisys

**Comment by kowalcj0** [comment]
@jenisys I think we can close this ticket unless you'd like to look into how this can be fixed without the need to re-order the step definitions?

**Comment by jenisys** [comment]
@kowalcj0 I try to look at it over the weekend. Therefore, I would like to keep it open until I have looked at it.

**Comment by jenisys** [comment]
@kowalcj0 
ANALYSIS:
Because you did not specify any type (or type-pattern) for your step-parameters, you fall into the greedy regular parameter-trap. The regular expression group for a parameter is ``.*`` (which matches anything and easily gets greedy, meaning it matches more than you think it should/would match). The first step definition matched the remaining step parts in parameter ``property_1``. If you fix the ``property_X`` parameters, the ``value_X`` parameters will have this greedy-match problem (without causing ambiguous step-definition errors).

You can avoid this trap by either:
* using concrete types for each step-parameter (simplest case for you: Use type=S)
* reversed step-definition (registration) order (from complex to simple step definition; as already stated above)

EXAMPLE: Provide a type for each step-parameter
```python
# Use type=S (match any non-whitespace chars)
@given(u'a resource with "{field_1:S} {operator_1:S} {value_1:S}" in "{property_1:S}"')
def step_impl(context, **kwargs):
    pass
...
```

**Comment by kowalcj0** [comment]
Thank you @jenisys 
It's as clear as possible to me now.
Maybe we could add something about it to the documentation?

**Comment by jenisys** [comment]
Not everything can be in the documentation. And types are already described there. Sometimes you need your own Eureka effect when you stumble over a problem and understand (or solve it) :smile:

If you have a good idea how to improve it, provide a pull-request.
