### ISSUE TITLE
Restore backward compatibility to Cucumber style RegexMatcher (due to #280, #282)

### ISSUE THREAD

**Issue by avabramov** [behave/behave#455]
changes introduced in #280, #282 have broken backward compatibility

steps to reproduce: 
1. say there is a following step: 
`@When(r'^I am on (\w+) page$')`
2. behave has been upgraded from 1.2.4 to 1.2.5
3. When tests are executed the following error occurs:
Actual result:
`AssertionError: Regular expression should not use begin/end-markers: ^I am on (\w+) page$`
(the assertion added in #280)  

The statement itself is incorrect as violates regex syntax. Regular expression may use begin/end markers and there is no reason not to support it as 're' step matcher was set. It is a part of regex power (power = complexity). If it appears to be too difficult to use, there are other step matchers.   

I see that in #282 these markers have been hardcoded into behave logic, but what if I already have them in definitions of hundreds of tests (it is my case actually)?

**Comment by jenisys** [comment]
Sorry, it does not make any sense that you use these start/end markers because the code provides them anyway (now). And the assertion was added to automatically detect the problem when the constraint is violated.
The start/end markers are unnecessary syntactic sugar that is always needed (and I would be really interested in a step definition that does not need them and why). So why type the start/end markers, let the framework add the necessary things.

Otherwise, if this functionality is so important, provide a pull-request which checks if the start/end-markers should be added and provide the corresponding tests for that.
As an alternative, you provide your own regular expression step matcher and use it.

**Comment by avabramov** [comment]
Thanks for the response. My point is that it is invalid to throw an assert error if there are these start/end markers, as they are a valid part of regular expression syntax. It is confusing.
Also there are people having these markers in definitions as I have. 
 I will make a pull request as it is really easier than fix all steps and then test the changes. I have hundreds of them.

**Comment by jenisys** [comment]
Sorry, I disagree regarding the usage of the assert statement. This is a "Design-by-Contract" verification that prevents that you provide a regular expression that violates the internal assumptions. That is much better than allowing hidden side-effects that would take you much long time to discover.

Out of curiosity:
* Why are you not using the "parse" or "cfparse" matcher ?
  They are in general much easier to use and provide type conversions.

**Comment by avabramov** [comment]
Keywords base was created for freshen and then migrated to bevave, as it is more flexible, works faster and has support.
We have lots of keywords so that rewriting to parse or cfparse is impossible. Also cfparse is not supported be intellijidea which is a huge disadvantage. 

So, with behave 1.2.4 everything was working, but after installing 1.2.5 it appeared that all keywords are not valid anymore.

**Comment by jenisys** [comment]
INTEGRATED INTO: behave-1.2.6.dev0
