### ISSUE TITLE
Certainly/unconditional teardown operation

### ISSUE THREAD

**Issue by vit1251** [behave/behave#479]
Let's talk about testing tails on database/filesystem or different one unclosed resource or operation.

When scenario is fail, then no way to revoke/close resource.

How about implement additional keywork like "Anyway".

```
Given http session
When make request with timeout 10 sec.
Then last request succes
Anyway close http session    <----- new line
```

Thanx.

**Comment by aisbaa** [comment]
Can you define http session? Is it [keep-alive](https://en.wikipedia.org/wiki/HTTP_persistent_connection) or application session using cookies?

**Comment by vit1251** [comment]
There is just example of test with memory/resource leack.

**Comment by aisbaa** [comment]
Is this what you're looking for: [#debug on error in case of step failures](http://pythonhosted.org/behave/tutorial.html#debug-on-error-in-case-of-step-failures)?

**Comment by vit1251** [comment]
@aisbaa no, I talking about fully automate actions. I does not expend some problem with case but I have no small feature for clean up after case I.e. It some thing like background but after not befor execution.

**Comment by jenisys** [comment]
@vit1251 
Actually, I think you can solve the problem on your own.
You just need to implement the "anyway" step correctly.

Another potential solution is (if you need cleanup actions):
* add the core cleanup functionality to the context object in the ``before_scenario`` hook
* register for cleanup (in your step implementations)
* perform cleanup (if necessary) in the ``after_scenario`` hook for any registered cleanup action

NOTE: Regarding ``anyway``
Step implementations are part of the step writer/provider.
``behave`` can take no part in it because only the step writer knows what needs to be done.

**Comment by jenisys** [comment]
Added context-cleanup and fixture concept.
INTEGRATED INTO: behave-1.2.6.dev0

**Comment by vit1251** [comment]
@jenisys could I ask you drive more in documentation about context-cleanup and fixture concept.

**Comment by jenisys** [comment]
@vit1251 This is already described in section "New and Noteworthy" or chapter for "Fixtures".

SEE ALSO:
* [docs/new_and_noteworthy_v1.2.6.rst](https://github.com/behave/behave/blob/master/docs/new_and_noteworthy_v1.2.6.rst#context-based-cleanups)
* [docs/fixtures.rst](https://github.com/behave/behave/blob/master/docs/fixtures.rst)
* [RTD: New and Noteworthy v1.2.6](http://behave.readthedocs.io/en/latest/new_and_noteworthy_v1.2.6.html#context-based-cleanups)
* [RTD: Fixtures](http://behave.readthedocs.io/en/latest/fixtures.html)
