### ISSUE TITLE
"json.pretty" format is not valid for "Jenkins plugin Cucumber-JVM reports "

### ISSUE THREAD

**Issue by illlych** [behave/behave#499]
1. Tags part of json should be like this: "tags": [ { "name": "slow" }]
2. Uri part of json should be like this: "uri": "features\\filename.feature"
3. Background part cause an error

Here json formatter to fix this:
[json.zip](https://github.com/behave/behave/files/514627/json.zip)

But if this format special to "Jenkins plugin Cucumber-JVM reports ", then add please new formatter, usage like "format=json.CucumberJVM" in "behave.ini"

**Comment by illlych** [comment]
Se also here:
https://www.relishapp.com/cucumber/cucumber/docs/formatters/json-output-formatter

**Comment by fredizzimo** [comment]
You are one day late, see #267. That issue has been open for two years though, and now there are two independent fixes in two consecutive days...

**Comment by jenisys** [comment]
DUPLICATES #267 (as @fredizzimo already said).

@illlych 
Thanks for your effort. But source code is normally provided as pull-request (in your case with a different filename). And note that your solution did not catch all of the differences (according to the discussion #267).

The core of the problem is that Cucumber has no specification of its JSON schema (at least not that I am aware of because I suggested such a thing a while ago). Yes, it has/provides examples (but these are incomplete). Therefore, the tools must do a reverse-engineering with various degrees of accuracy.
Note that behave has at least a JSON schema.
