### ISSUE TITLE
Better support for running Behave programmatically from Python

### ISSUE THREAD

**Issue by realcundo** [behave/behave#501]
We're running Behave from our automated testing framework and at the moment we have to resort to a hacky way to integrate it with Behave.

While I know that behave was not meant to be used a library, two simple additions would allow anyone to subclass and customise Behave behaviour:
- ability to specify subclassed `Runner` class when calling `behave.__main__.main()`. This would allow us to use custom `Context` (with helper properties for users/browsers/connections); initialise Features and Steps from non-standard locations (VCS/DB) and register extra Formatters/Reporters.
- ability to pass in `Configuration` object to `behave.__main.main()` instead of just `args`. This would let us define defaults that make sense to us instead of passing in the same arguments every single time. Another benefit is that we could pass in a subclased `Configuration` instance that could be used by the derived `Runner` class (extra command line parameters, reading the configuration from other file formats).

Example `behave.__main__.main()` implementation:
```python
def main(args=None):
    config = Configuration(args)
    return main_custom(config)


def main_custom(config, runner_class=None):
    assert config is not None

    # use default Runner class
    if runner_class is None:
        runner_class = Runner

   # the rest of old main() goes here
   # ... 
    runner = runner_class(config)
   # ... 
```

There's more that could be done, but I think this is the minimum/least invasive change to make Behave usable programmatically.

Let me know how does it sound to you, I can send you a pull request.

**Comment by jenisys** [comment]
@realcundo 
Well, if it you be so easy, you could already provide your solution for yourself ;-)
The core problem is that you currently share module specific instances (related to step and environment imports). These are basically the step registry and type registry related to the matcher. First steps have been taken to clean this up. Providing a library support makes only sense afterwards. Currently, you can use the library approach only when you use sequential execution and make the required cleanup steps at the correct time.

SEE ALSO:
* #264 for a related discussion
* [behave._stepimport](https://github.com/behave/behave/blob/master/behave/_stepimport.py) module with one part of the underlying core functionality
* Example how this can be used: [tests/api/_test_async_step35.py](https://github.com/behave/behave/blob/master/tests/api/_test_async_step35.py)

**Comment by realcundo** [comment]
Thanks for the links. I don't really need anything that complicated. :)

All I meant was a basic decoupling of the parameters parsing (i.e. instantiating `Configuration)`, evaluating the config and printing help and running (`Runner(confing).run()` + catching exceptions).

At the moment all 3 happen in the same long function. If not splitting it into 3 parts, even 2 parts like the example I provided would help.

My use case is that we have a wrapper around Behave which has different default config options than Behave. The wrapper tool can also take Behave's command line parameters. If I didn't care about Behave's command line parameters at all, I would instantiate `Configuration` and `Runner` directly. Allowing to supply Behave's parameters (including help options) to our wrapper tool makes things more flexible.

If you don't think decoupling is a good idea, I'll live with that. :)

**Comment by fredizzimo** [comment]
I would like to see this as well. 

If I understand @jenisys correctly, the problem is that for example the `registry` variable in https://github.com/behave/behave/blob/master/behave/step_registry.py, is global to the module, so when you start another runner, the old step definitions would still exist.

However even with this limitation I think a better api for running the tests would be beneficial. The limitation would be that you can't change the features and step directory.

**Comment by jenisys** [comment]
Basic support added.
INTEGRATED INTO: behave-1.2.6.dev0

**Comment by fredizzimo** [comment]
@jenisys, Thanks, it looks like 8686820899a8f86b6c6b0ceebedbcc3f9a033d01 contains most of the needed fixes for this, at least when it comes to doing batched runs with different parameters.

For speed of testing, it might be better if we were allowed to select if the steps registry and other things should be reset or not though.

What it doesn't really support is to add more complex running logic, even though the runner class can be specified. The problem there is that most of the actual running logic is inside the model classes instead of the runner, so there's very little that you currently could potentially overload. For me this is not a problem, at least not right now, and I'm not even sure if it would be a good idea to allow it, even if it would make it possible to do things like, for example but not limited to, randomized test order, or skipping based on some more advanced criterion than the tag.

Another minor problem I see and that wasn't directly asked in this issue, is when subclassing config, or even without doing that when you have your own way of launching tests, you might want to modify the list of supported command line arguments, which doesn't seem to be possible through the api. It is however possible to do so by monkey patching the `configuration.options` array, so I'm not sure if it should be classified as a bug or the correct way of doing it.

**Comment by realcundo** [comment]
Thanks @jenisys, that helped me. :)

I don't really need the runner reset bit as what we do is to run behave in parallel as separate instances, each running its subset of features. The only time when I care about re-registering steps is when tests are run interactively from IPython/Jupyter and it's simple enough to supply my own `given`/`when`/`then` decorators doing the minimal cleanup/reset.

@fredizzimo if you want to randomise tests or skip them, you can simply subclass `Runner` and override `run_with_paths()` where you can initialise the model the way you want (almost). In our case we reduce `runner.features` list before calling the base class. You could simply shuffle the list if you wanted.

It wouldn't be nice but you could also re-instantiate all `Feature` and `Scenario` instances with your subclasses and override `should_run()` methods if you wanted more fine grained control what is run and what is skipped. In my case we're happy with simple removal of unneeded features/scenarios.

**Comment by jenisys** [comment]
@fredizzimo 
As I stated above "Basic support added".
And its no bug, "its a feature" (in big-blue words) :wink:
I am well aware of the "features" and deficiencies of the configuration module.
And you can always provide a pull-request.

**Comment by eshansingh** [comment]
@jenisys Hey, I was wondering if these changes could be integrated into the non-dev version by now.
