### ISSUE TITLE
Behave stops on error

### ISSUE THREAD

**Issue by Abdoctor** [behave/behave#506]
I found an error which can lead to behave exit and it is not a syntax error. Test run it should not be stopped, because there is many other test scenarios. Is there way to fix this problem?

An error in my situation happens in `traceback` module - it tries to initialize `TracebackException` when `exc_value.__cause__` has not `__traceback__` attribute. So it leads to behave process exit with code 1

**Comment by jenisys** [comment]
You need to provide more context information:
* Provide a simple example with the observed output !
   behave normally states which exception is caught in the main function.
* Which behave version are you using ?
* Which Python version are you using (on which platform) ? 
  Maybe, Python 3.5 due TracebackException was added in Python 3.5

**Comment by Abdoctor** [comment]
Sorry, I forgot to specify:

- Behave 1.2.6.dev0
- Python 2.7.12

And there is more information about exception (actually it happens in Django app, using behave-django):
`IntegrityError: null value in column "blah" violates not-null constraint
DETAIL:  Failing row contains (data)
`
Last line executed in Behave [here](https://github.com/behave/behave/blob/master/behave/model.py#L1339)

Django [bug](https://code.djangoproject.com/ticket/23643) is already fixed but I can't upgrade and change anything except testing tools.
Close example to reproduce https://github.com/Abdoctor/behave/commit/b0bc15eba8330352996f317f79987d06e5c4e978#diff-47b6187045502613f55c2c3e2f570421

**Comment by jenisys** [comment]
@Abdoctor 
You use a Python3 feature that is not really supported in Python2. Therefore, Python stumbles and behave stumbles too because it does not expect such a problem in this place. And that is especially sensitive when it happens during exception processing.

But this problems seems to partly caused by you (at least in your example).
Therefore, if you use the "__cause__" with exceptions, you can also fix the problem in your code
(by setting the "__traceback__" attribute there) which is probably only needed in Python2.

In addition, your feature file makes only moderately sense.
The first two steps are not used in any sensible way during the execution of the scenario.
The third step has no step definition (as far as I can see).
Only the last two steps may make sense.

**Comment by jenisys** [comment]
This seems to be a ``traceback2`` problem.
See also: https://github.com/testing-cabal/traceback2/issues/7

**Comment by Abdoctor** [comment]
@jenisys 
Thank you for good explanation and updates.
