### ISSUE TITLE
Idea: have Feature.run() store or return the number of fails

### ISSUE THREAD

**Issue by althonos** [behave/behave#509]
Current `Feature.run` method keeps track of the total amount of failed steps, yet only returns a boolean:
```python
def run(self, runner):
    failed_count = 0
    # ... #
    failed = (failed_count > 0)
    return failed
```
It is therefore impossible to access to the number of failed tests for that feature.

One solution would be returning directly `failed_count` (the boolean interpretation would be consistent) or storing `failed_count` as an attribute of Feature.

I can PR a patch if needed.

**Comment by jenisys** [comment]
The ``failed_count`` is currently the number of failures that occur while running the feature. This maps in most cases to the number of failed scenarios (but not failed steps as you suggested). Because there are additional reasons why failures occur, it makes not real sense to change it to the meaning you suggest. You can easily retrieve the suggested information directly from the model after the test run.

**Comment by althonos** [comment]
Ok, nevermind.
