### ISSUE TITLE
Scenario Outline modifies tags

### ISSUE THREAD

**Issue by borbamartin** [behave/behave#513]
Hey there,
I have implemented a special tag functionality which allows me to exclude scenarios in this way:

@excluded_environments(QA,UAT,STAGING)
Scenario: ST-1593: Article State validation
...

This works just fine when running a normal scenario, however, this particular tag is being modified when running a scenario outline.

**Content of corresponding index of scenario.tags on simple scenario:**
"_excluded_environments(QA,UAT,STAGING)_"    ✅ 

**Content of corresponding index of scenario.tags on scenario outline:**
"_excluded_environmentsQAUATSTAGING_"    ❌ 

This is blocking me from parsing the excluded environments, and despite I've implemented a temporary fix, would be nice to have it working with the expected behavior 🤒 

I'm using Behave 1.2.5 (latest on pypi)

Any idea why this is happening and when it may be fixed? 

Thanks!

**Comment by jenisys** [comment]
Currently, the ScenarioOutline does not allow special characters, like: "(", ")", "," and so on
The main reason is that the ScenarioOutline is basically a template. For safety, certain constraints are currently used to prevent you from shooting yourself into the foot (what you have currently done, because the function-like syntax never reaches the Scenario model elements.

BETTER USE: Active tags, like
```gherkin
# -- FILE: features/example.feature
Features:

  # -- INSTEAD OF: @excluded_environments(QA,UAT,STAGING)
  # USE:
  @not.with_environment=QA
  @not.with_environment=UAT
  @not.with_environment=STAGING
  Scenario: ST-1593: Article State validation
```

SEE ALSO:
* [behave docs: New and Noteworthy v1.2.5: Active Tags](http://pythonhosted.org/behave/new_and_noteworthy_v1.2.5.html#active-tags)
* [features/tags.active_tags.feature](https://github.com/behave/behave/blob/master/features/tags.active_tags.feature)
