### ISSUE TITLE
Dynamic examples

### ISSUE THREAD

**Issue by adamatan** [behave/behave#517]
Hi,

I've asked [this question on Stackoverflow](http://stackoverflow.com/questions/41566294/behave-writing-a-scenario-outline-with-dynamic-examples), and thought it might be a good idea to suggest a feature here. If you think it's a good idea, will be happy to contribute code.

I want to run some Scenario Outlines with Examples that contain confidential information (e.g. user ids or SSNs). Puting such information in a static is a bad idea for security reasons, as wall as modularity reasons (user ids in staging might not work on prod).

Is there an elegant built-in way to dynamically generate the list of examples in a feature file?

**Comment by jenisys** [comment]
@adamatan 
After looking at Stackoverflow question, I do not think that you need dynamic examples. You just need to retrieve the sensible data by using something like an ID (for example, a key-id). If you have a secure key storage, you have a similar problem. You want that nobody can access the keying material but you need something to refer to it, so that it can be used (behind the scenes).

A tool that may help you, could be the userdata concept.
Otherwise, a step implementation could retrieve the sensible data by using the ``key-id`` or something similar.

SEE ALSO:
* [features/userdata.feature](https://github.com/behave/behave/blob/master/features/userdata.feature)
* [docs: New and Noteworthy: Userdata](http://python-behave.readthedocs.io/en/latest/new_and_noteworthy_v1.2.5.html#userdata)

NOTE:
I am not suggesting that you should put, official passwords or similar sensible data as plain text into configuration files. For testing, it is often better to use a special "test domain" that just proves that the basic principle works correctly.

**Comment by adamatan** [comment]
Thanks a lot for the reply.
