### ISSUE TITLE
Extension request: behave-flask

### ISSUE THREAD

**Issue by fkromer** [behave/behave#521]
Are you planning to implement an integration into flask comparable with [behave-django](https://github.com/behave/behave-django)? I would be interested in contribution.

**Comment by jenisys** [comment]
Sorry, I am currently to busy with other stuff. Therefore, I am personally not planning to support it.
But you can either provide it on your own (starting a new repository for this) or ask @bittner and/or @mixxorz (behave-django core team) if they are interested. Maybe others are interested too.

**Comment by bittner** [comment]
Why `behave-django` Integration Is Easy
----------------------------

The "integration magic" of behave-django is mostly via things that Django provides.

- The essential part is Django's [`StaticLiveServerTestCase` class](https://docs.djangoproject.com/en/stable/ref/contrib/staticfiles/#specialized-test-case-to-support-live-testing) that spins up a runserver (so you don't have to spin up a Django instance yourself, manually, before you execute `behave`).
- What we do is actually [prevent Django from running its test suite](https://github.com/behave/behave-django/blob/master/behave_django/testcase.py#L11-L12) (because `behave` runs from outside).
- In the end, we [hook into](https://github.com/behave/behave-django/blob/master/behave_django/environment.py#L56-L65) the `behave` executable [when you run it](https://github.com/behave/behave-django/blob/master/behave_django/management/commands/behave.py#L107-L109) via a Django [management command](https://github.com/behave/behave-django/blob/master/behave_django/management/commands/behave.py#L77-L78). Django provides [this management command](https://pythonhosted.org/behave-django/usage.html#command-line-options), because you add `'behave_django',` to the `INSTALLED_APPS` interable in a Django project's [settings module](https://pythonhosted.org/behave-django/installation.html).

All this is practically Django. We're hooking into Django infrastructure.

What Would `behave-flask` Need to Do?
-----------------------

If you want to do the same thing for Flask the setting is a bit different. There is nothing like that provided by Flask. Simply because Flask doesn't need it. It relies on things that are out there in the Python eco system---**but**, you have to choose them.

The [Flask documentation](flask.pocoo.org/docs/latest/testing/) on testing is actually helpful and very specific on choosing Python's `unittest` module. If I started trying to integrate behave and Flask I would start from there.

Other than that I don't see any logical, intuitive point to jump into to make it specifically easy for developers using Flask to run behave. (There is no such thing as Django's `INSTALLED_APPS`, for example, in Flask.)

What We Do In Addition
---------------------

More than just the technical bits of integrating behave into Django we also provide

- [practical tips on testing](https://behave.readthedocs.io/en/latest/django.html) via the behave documentation.

What We Could Do For Flask
-------------------------

From my point of view we should:

1. **Start with a Flask chapter** in the behave documentation, providing a detailed yet concise hands-on approach on running behave with Flask. (In there, point to the Flask documentation, and maybe have the Flask documentation point  to us.)
1. Try to figure out which parts of the documented approach **make sense to automate**. (Less code, less hassle, less room for errors.)

More than that:

- We should extract the general, [practical information on testing](https://behave.readthedocs.io/en/latest/django.html#automation-libraries) (that is not specific to Django) from the Django chapter in the behave docs, **creating a consolidated** _Practical Tips On Testing_ **chapter**, and two concise chapters for both Flask and Django.

That would by sexy.

**Comment by fkromer** [comment]
Thanks a lot for this hints! As I have not really used Django until now (despite of playing arround with it a bit) I did not really understand everything. However the documentation part would help a lot of people to apply/ease implementing bdd style acceptance testing in flask.

**Comment by bittner** [comment]
Can you provide a PR for that?

Simply add a `flask.rst` file in the [docs folder](https://github.com/behave/behave/tree/master/docs), and add a reference to the `flask` chapter to the "Contents" section [in the index](https://raw.githubusercontent.com/behave/behave/master/docs/index.rst).

**Comment by fkromer** [comment]
@bittner @jenisys @mixxorz Alright. I'll try to find some time during the next weeks to add a "flask" section (maybee after the "Django Testing Example" section).

**Comment by bittner** [comment]
Willing to enhance the documentation, anyone?

**Comment by fkromer** [comment]
@bittner Unfortunately this is no priority for me right now.

**Comment by jenisys** [comment]
If anyone is willing to work on it, we can reopen the issue.
