### ISSUE TITLE
How can i use external file to provide the data instead of define tables in the feature file

### ISSUE THREAD

**Issue by XiangyueHe** [behave/behave#531]
Normally we have to defined a table like below in the feature file:
| ip | port |
| 1.1.1.1 | 1000 |
| 2.2.2.2 | 1001 |

while i want to provide the data from a separate external file, how can i do it.

**Comment by jenisys** [comment]
Just implemented the second step in the following example.

Example:

```gherkin
Given the server configuration:
  | ip      | port |
  | 1.1.1.1 | 1000 |
  | 2.2.2.2 | 1001 |
And I read additional table data from the configuration file "network_services.json"
...
```

**Comment by jenisys** [comment]
Otherwise, use the [userdata](http://behave.readthedocs.io/en/latest/new_and_noteworthy_v1.2.5.html?highlight=userdata#index-7) concept to provide the data and decide in the steps which part of the data should be used.

SEE ALSO:
* [docs:New and Noteworthy v1.2.5 -- Userdata](http://behave.readthedocs.io/en/latest/new_and_noteworthy_v1.2.5.html?highlight=userdata#index-7)
* [features/userdata.feature](https://github.com/behave/behave/blob/master/features/userdata.feature)

**Comment by mkusz** [comment]
You can also do something different.
Create an decorator that will decorate your python step implementation.

> @when(u'Your step with "{variable}"')
> @decorator
> def step(context, variable):

Then in decorator `args[0]` will be your context and any variable will be in `kwargs`. This way you are able to replace variable value before execution and read external data.
