### ISSUE TITLE
How to add image/png:base64 in json report?

### ISSUE THREAD

**Issue by malamud** [behave/behave#546]
Hi!

I would like to add an image to see it after test finished in jenkins cucumber report plugin.
This kind of feature is in cucumber and cucumber jvm to embed report with some image in base64.

```ruby
encoded_img = @browser.screenshot.base64
embed("data:image/png;base64,#{encoded_img}",'image/png')
```

```java
scenario.embed(screenshot, "image/png");
```

Also there is method in Behave
[behave/behave/formatter/json.py](url)

```python
def embedding(self, mime_type, data):
    step = self.current_feature_element["steps"][-1]
    step["embeddings"].append({
        "mime_type": mime_type,
        "data": base64.b64encode(data).replace("\n", ""),
    })
```
How to use this one in test step?

**Comment by jenisys** [comment]
You don't because that would be rather bad.
The functionality that you are asking for is currently not supported yet.
The ``embedding()`` method in the JSON formatter is prepared, but the remaining infrastructure that makes it easily usable is lacking.

For now, write the "annotations" (like screenshots) to another file with enough context information that allows you to merge it with the JSON output outside of ``behave``.

**Comment by malamud** [comment]
I got it. Thank you.

**Comment by lbsfei** [comment]
@malamud,
I have same issue with you, pls help me, thanks!

**Comment by QA-Rahul** [comment]
Any workaround here? I am looking for the same.

**Comment by QuentinDEME97** [comment]
Hello, still no update ?

**Comment by jenisys** [comment]
@QuentinDEME97
The curious one looks around and finds something relevant.
Maybe you should look at #959 (for example).
