### ISSUE TITLE
flake8 reports F811 redefinition of unused 'step_impl'

### ISSUE THREAD

**Issue by bittner** [behave/behave#574]
Ignore F811 for duplicate `step_impl` functions ...
-------------------------

I'm using flake8 to check my source code, and I've been ignoring the typical [F811 redefinition violation](http://flake8.pycqa.org/en/latest/user/error-codes.html) globally in the past. I'd really prefer not to ignoring violations at all, so I've browsed the [behave docs](https://pythonhosted.org/behave/search.html?q=step_impl&check_keywords=yes&area=default) whether using the default `step_impl()` function name is actually the recommended approach.

... to silence false alarms
-------------------

While I've not seen an explicit confirmation of this I've seen `step_impl` being used exclusively for all occurrences of feature step implementations. I understand (or rather believe) that the behave decorators change the signature of the `step_impl` function, so that technically they are all different functions even if they have the same name in the source code (hence "redefinition" is a false alarm). I also believe that's the reason why Pylint doesn't report this as an error, because flake8 performs static checking only (hence has its limits).

Don't import decorators (... and get more violations)
------------------------------

Interestingly, reading the docs I found the following paragraph in the [API chapter](http://behave.readthedocs.io/en/latest/api.html#step-functions):

> _You don’t need to import the decorators_: they’re automatically available to your step implementation modules as global variables. (dead link)

Following this advice I obviously get another violation reported:

``` bash
$ flake8 
./tests/acceptance/steps/given.py:9:2: F821 undefined name 'given'
./tests/acceptance/steps/given.py:26:1: F811 redefinition of unused 'step_impl' from line 9
./tests/acceptance/steps/given.py:26:2: F821 undefined name 'given'
./tests/acceptance/steps/when.py:7:2: F821 undefined name 'when'
./tests/acceptance/steps/then.py:6:2: F821 undefined name 'then'
```
Maybe it's of interest to note that I had `from behave import given` (etc.) in the implementation modules; I prefer not to do the discouraged `from behave import *` import.

What's the right way?
-----------

Now, if I wanted to do it all right what should I do (to make the code PEP8 compliant, obviously)?

1. Give every `step_impl` function a unique name, manually? (... and update the behave docs)
1. ... and do behave imports? (... and update the behave docs)
1. Or write a flake8 plugin or configuration recommendation to silence the violations on valid step implementation code?

**Comment by bittner** [comment]
See also:

- [flake8 Plugin For Behave](https://gitlab.com/pycqa/flake8/issues/345) (flake8 issue tracker on GitLab)

**Comment by jenisys** [comment]
**Step function names:**
Step function names do not need to have a unique symbol name, because the text matching selects the step function from the step registry before it is called as anonymous function. Using the same name for all step functions makes it easier to print-out the missing step implementations (all with the same name "step_impl").

When you actually want to call a step function directly (normal function call in Python), the the called step function needs a unique name. Therefore, my step functions often have a unique name. In addition, you can now directly check step functions in unit tests (to verify that the step implementation is correct; often needed or sensible if you provide step libraries). In addition, stack traces may be more readable.

SEE ALSO:
* [behave4cmd0/command_steps.py](https://github.com/behave/behave/blob/master/behave4cmd0/command_steps.py#L157) (example: step_i_successfully_run_command())

**Import of step decorators:**
While behave injects some symbols historically (like the step decorators) when a step module is loaded, I personally import what I need in step modules. This allows me to use any static code analyser (like pylint, flake, etc.) to check if my code is correct. Otherwise, you need to make the static code analyser aware of the implicit symbols (the "flake Plugin for Behave" solution).

**Comment by bittner** [comment]
Thanks für the comprehensive explanation.

Re "Step function names": We should probably add this information to the docs somewhere.

Re "Import of step decorator": The docs currently suggest not to import the decorators. Even worse, they suggest to do `from behave import *`, which is not en vogue anymore. We should probably rectify this, shouldn't we?

Even if decorators are imported - which is helpful for (code navigation in) IDEs too, for example - we need to provide some level of "behave awareness" of linters (flake8, pylint) when the function names stay identical in a single module. This is probably unavoidable, isn't it?

**Comment by jenisys** [comment]
Regarding the first two points. If you have time to provide a pull-request to improve the documentation... Otherwise, I will try to have a look at it. [behave.example](https://github.com/behave/behave.example) already follows my description in all or most cases.

Regarding "behave awareness" in linters: Up to now I was pragmatic to avoid these problems. But I agree, it is a good idea to be able to use linters to check your code.

**Comment by aspiers** [comment]
I appreciate the work which went into #579, but I don't really see how https://github.com/behave/behave/pull/579/commits/a3cb0ffe4fdb840f2942f270cf9fcca31cad8c0e resolves this issue.  That change essentially says "step function names don't need to be unique", but it's still unclear to me what the recommendation is for avoiding F811 failures from flake8.  Is it:

1. Configure flake8 to ignore F811? (which would not be ideal because it would risk ignoring genuine redefinition issues elsewhere)
2. Rename each `step_impl` to something unique?
3. Something else?

I think it would be better to make an explicit recommendation on how to handle this, or perhaps even better, change behave so that it makes each stub `step_impl` implementation auto-generated by `behave` unique, by auto-suffixing with increasing integers, e.g.:

```python
You can implement step definitions for undefined steps with these snippets:

@given(u'we have behave installed')
def step_impl1(context):
    raise NotImplementedError(u'STEP: Given we have behave installed')


@when(u'we implement a test')
def step_impl2(context):
    raise NotImplementedError(u'STEP: When we implement a test')


@then(u'behave will test it for us!')
def step_impl3(context):
    raise NotImplementedError(u'STEP: Then behave will test it for us!')
```

**Comment by jenisys** [comment]
`flake` thinks it knows better than the Python interpreter/runtime.
=> FALSE-POSITIVE

**Comment by bittner** [comment]
I believe, the proper way to address this issue is writing a flake8 plugin that properly analyses and silences the occurrences of the current violations.

[flake8-django](https://pypi.org/project/flake8-django/) is an example of such a beast. Yet still, that would only make sense of such plugins can be mixed (e.g. I would use both `flake8-django` and `flake8-behave` at the same time, none should <strike>override</strike>compromise the behavior of the other).

Maybe we could trigger this in a sprint on a Python or testing conference?
