### ISSUE TITLE
Why behave exited with status code '0' on assertionFail? (mine fail on @then)

### ISSUE THREAD

**Issue by tangorboyz** [behave/behave#583]
I have this problem integrating behave for my django project with travis-ci. There is assertion failure on @then tag but travis report that the test pass (unexpected). But django test return status code '1' on test failure which cause travis to report test failure (as expected).

**Comment by tangorboyz** [comment]
Sorry, maybe because I start behave from python script?
My script like following:
`from behave.__main__ import main as behave_main`
`
behave_main("./features")`
On "script" section of .travis.yml I put like "python behave_run.py"
I replace that line with "behave", then it return status code 1 (build failed)
Forgive me, it's a mistake

**Comment by tangorboyz** [comment]
I run behave from python script because I have behave installed on multiple python version (2.7, 3,5, 3.6). I think, maybe I could run it like "python3.6 behave_run.py"

**Comment by jenisys** [comment]
Have you now resolved your problem or do you still have it ?!?

If the original behave script does no have the problematic behaviour, the problem is in your script.
I assume you should use ``sys.exit(behave_main()``. Otherwise, you will not get the correct result code, AFAIK.

SEE ALSO:
* [bin/behave](https://github.com/behave/behave/blob/master/bin/behave)

NOTES:
* If you have installed ``behave`` for each python version, you should not have a problem with your original script.

**Comment by tangorboyz** [comment]
already resolved.
