### ISSUE TITLE
HOOK-ERROR in after_step: AttributeError: '_RunnerWrapper' object has no attribute 'log_capture'After scenario

### ISSUE THREAD

**Issue by ionakathryn** [behave/behave#589]
`HOOK-ERROR in after_step: AttributeError: '_RunnerWrapper' object has no attribute 'log_capture'After scenario`

Hi I am doing a basic tutorial with behave using Selenium and getting this error message when trying to click on 'about' link. Can anyone suggest what is going on? I am using PyCharm to run this and I am using Python 3.6.2 and I am using Mac OSX

Thanks

**Comment by jenisys** [comment]
Because the behave repository, does not contain any ``_RunnerWrapper`` in python files, I assume the problem is in your code.

**HINT:**
Lint your Python step implementations (or any code) that is imported by them (for example with pylint).
This requires that python step decorators, etc. are imported in your step files, like:

```python
# -*- coding: UTF-8 -*-
# FILE: features/steps/my_steps.py
from behave import given, when, then, step
...
```

**Comment by ionakathryn** [comment]
Yes the problem was in my code. This seems like a generic error and I have to run in debug mode to find out what the problem actually is.

What do you mean to lint the Python step implementations? I was using:

from behave import *

But this wasn't the issue. The issue was with my code. It would be great if this error gave more specific information though, without the need to debug.
