### ISSUE TITLE
Steps using data-types are not checked as Ambiguous

### ISSUE THREAD

**Issue by alluir42** [behave/behave#598]
Hi,

It seems that matcher.match is used BOTH when a) trying to match a step in a scenario to a step definition and b) two step definitions against each other to see whether they are ambiguous.

Typically data types are written such that they think about what arguments are they taking, but they do not to match themselves. For example if the data type is hooked to a function, that function will receive as input the variable name and variable type as input "{no_of_apples:Num}", when trying to look for duplicate steps. This is further limited if a data-type has @with_pattern restrictions, then typically it will not even TRY to match a step with itself, because typically a string like "{no_of_apples:Num}" will not match "\d+".

If I have these two step definitions they are not considered ambiguous: 
@then(u'there are {no_of_apples:Num} of apples in the basket')
and 
@then(u'there are {my_date:Date} of apples in the basket')
and both Num and Date are connected to functions that can take any string input (so have no @with_pattern restrictions). 

Basically the parse_type-s are not self-aware. I've been trying to create my own limited version of parse_type (make_enum and make_choice), with functions that recognize themselves, but it is swirling out of control very fast. I don't know what would be a good solution to this. Currently I'm adding extending any @with_pattern with something like |(\{[a-zA-z_0-9]+:MyType.?\}) and calling this function at the beginning of each data type function:

```
def _checkmyself(value, typ):
    """
    Data Types have to be aware of themselves. When the behave step matcher compares to steps it actually calls the functions as well with the argument NAME example: '{arg_name:ArgType}' and not an expected VALUE.
    """
    # not a datatype
    if len(value) < 1 or not (value[0] == "{" and value[-1] == "}"):
        return False
    
    # I have to be myself, do not allow multiple datatypes with same step text
    assert value.find(":%s" % (typ)) > 0, "Trying to register the same step with a different input data_type %s [%s]" % (value, typ)
    return True
```

Does this make any sense? Unfortunately we are relying heavily on the duplicate step-definition detection, so have to find to get it working somehow.

**Comment by jenisys** [comment]
Have you looked at [behave.example: step_matcher/multi-methods](http://behave.github.io/behave.example/step_matcher/use_multi_methods.html) ?

In general, you should not make it more complicated than that (in the example above). Note that the ordering of the step definitions is by intention (and is important) because it is the decision logic for finding the correct step.

You cannot have two types that are basically numbers (by regex pattern), but your type name differs.
The regular expression of two numbers is normally the same.  
``parse_type`` already provides you w/ at lot of functionality to compose types and regex pattern from other "types" (conversion functions) and their patterns.

There basically two approaches (when you want to use type converters):

1. Basic (default) ``pattern=".*"`` matches anything and your type converter takes care of the rest.
   BUT: Your steps / step-language design must avoid ambiguous steps (by intention).
   AND: It is often a good idea to quote parameters to avoid lurking regex problems (match too much..).
2. You have rather good matching patterns for your data types.
   BUT: Now some steps will not be found at runtime (use: dry-run mode to check), because the text does not match the regex pattern.

Another idea could be to have specific decorating words to mark a data type in step.
For example, SI units are good to mark specific data types (that are mostly numbers).

And always remind yourself:
It is a two step procedure:
1. The regex pattern is matched to try to find the best matching step definition
2. Then the type converters for this step are applied to the placeholders 
    (and the type converters can not go back to step 1)

NOTE: If you have an idea how to improve the ambiguous step situation, give me a hint ...

**Comment by alluir42** [comment]
Hm, perhaps some more background, why this is important for us. We are using behave as an "API", so that tests can be shared between several platforms. What this means is that step definitions are actually overridden - there is a shared abstract API layer and there is an implementation layer for steps with different implementations - the connection between the two is to have the same step decorator. We are relying on the matching (using a wrapper for the given/when/then decorators), so that the implementation layer can see that this is the same step, and providing actual implementation to an abstract API step.

This does not seem to go too well with what is described in the multi-methods :(. At least at the moment :). With my current setup it would actually throw an exception on the Fruit input, that you have already defined this step with Vegetable input.)

Thank you for your input, I will have to think about it more. If you have some more ideas, given this background, please feel free :). Behave is awesome, that is why we decided to go with this setup, it is only me who does not know enough of all the intentions and internal workings of it :).

**Comment by alluir42** [comment]
I have been thinking a while and realized I'm just over-complicating things. Instead of using the matcher.match to detect if a step is the same, I just say that the matcher.string has to be the same, which we probably need anyway, so that the input-argument names do not get changed in the process. And when it comes to deciding which similar-sounding step to use (as described in multi-methods), we'll rely on behave's current behavior with no additional magic.

Thank you very much for your help :).

**Comment by jenisys** [comment]
@stalebot
Remains open.

**Comment by jenisys** [comment]
@stalebot
Remains open.

**Comment by jenisys** [comment]
@stalebot
Remains open.
