### ISSUE TITLE
Support for --tag-include= and --tag-exclude= to allow CLI options to add to ini options

### ISSUE THREAD

**Issue by jacobSingh** [behave/behave#605]
Here's my use case:

Scenarios are tagged per platform.  One feature may have some tests executed in our JAVA web automation repo and some tests executed in our python integration testing repo (along with the code).  Scenarios are also tagged for their purpose (regression, smoke, Issue-1234, etc).  If I pass in the tag for the purpose, I would override the ini file.  I want to add to it.

Given a behave.ini file contains 'tags="python"'
And there is a scenario "Scenario 1" which is tagged "@python @regression"
When I run behave with --tag-include="regression" on the command line
Then the scenario "Scenario 1" is run

**Comment by jenisys** [comment]
Do you understand the tag-logic with logical-and and logical-or expressions ?

In the configuration-file, you should only use ``default_tags``.
You should not use ``tags`` because this parameter uses append logic than cannot be taken back.
Therefore, configuration-file ``tags`` and command-line`` are appended together forming a logical-and expression.

SEE ALSO:
* [behave.example/tutorials/tutorial11.html](http://behave.github.io/behave.example/tutorials/tutorial11.html)  (Using tags)
* [features/runner.tag_logic.feature](https://github.com/behave/behave/blob/master/features/runner.tag_logic.feature)
