### ISSUE TITLE
Generate skeleton steps files based on features

### ISSUE THREAD

**Issue by rafaeldelucena** [behave/behave#607]
Hello,

I would like to know if there is any way to generate skeleton step files using the feature files.

Best regards

**Comment by spyoungtech** [comment]
Can you give an example of what you might expect a skeleton file to look like provided a feature file of undefined steps? Or examples of other BDD frameworks (from any language) that do this?

Here are my thoughts... It would probably be possible and relatively easy to do, but probably limited in usefulness in my estimation. Currently, if behave encounters unimplemented steps, it will produce the text that amounts to this feature for each unimplemented step. For example if you have the feature step 

```
When I do "foo" with "bar"
```
Behave will let you know this is unimplemented and suggest you define it and even produce some sample code similar to

```python
@when('When I do "foo" with "bar")
def step_impl():
    raise NotImplementedError('Step not implemented')
```
It is easy enough to copy/paste (or even script against) to get this in a step file. However, it's limited because it will not produce steps with patterns.

For very simple cases, it may be possible to detect simple patterns. For example, perhaps simple patterns could be generated by defining text between double quotes as variables. So, using the same feature from above, the automatically generated pattern might look something like

```python
@when('I do "{arg1}" with "{arg2}"')
def step_impl(arg1, arg2):
    raise NotImplementedError('Step not implemented')
```

And this automatic generation would, of course, only occur if another feature step does not match a pattern that has already been established by another automatically generated step.

Beyond this, I'm not sure how much can be done before it gets nontrivial.

**Comment by jenisys** [comment]
As @spyoungtech already explained, the basic functionality is already provided. In addition, I agree with his explanations. There are several things that are not easily solvable:

* parameter detection / extraction (with type deduction)
* step organisation: split-up into multiple step modules, grouping and their names

Therefore, step implementation is manual task because you need to make some decisions. The step snippets for missing/unknown steps are a simple solution to get you started. But you normally adapt the snippets after you have copied them into a steps file.

An approach would be to provide a "MissingStepsFormatter" that writes your missing steps into a step file. But you need to make some assumptions to solve the problems that are mentioned above. Or you basically write the step snippets for missing steps to a steps file.

**Comment by simon-k** [comment]
SpecFlow for Visual Studio can do this, and it is extremely usefull

**Comment by jenisys** [comment]
@simon-k 
Does it work for plain steps (only a string) or steps with parameters ?

**Comment by aliBordbar1992** [comment]
@jenisys Actually yes, SpecFlow generates the steps with parameters, even it could recognize tables.
