### ISSUE TITLE
Support assert introspection like pytest

### ISSUE THREAD

**Issue by jorjao81** [behave/behave#610]
First of all, thanks for the great work with behave, it's really useful.
I have a suggestion to improve it even further:
Pytest introspects our assertions and shows a pretty, readable message of what went wrong. It would be great to have such a feature in behave.

**Comment by jenisys** [comment]
Have you looked at [behave-pytest](https://github.com/ribozz/behave-pytest) ?!?
This solution enables pytest assertions in behave (already).

NOTE:
Behave currently does not provide such a functionality because there already so many assertion/matcher libraries out there: 
http://behave.github.io/behave.example/intro.html#select-an-assertion-matcher-library
