### ISSUE TITLE
Is the next release going to be any time soon?

### ISSUE THREAD

**Issue by eserge** [behave/behave#617]
It's been a while since the last release of `behave`. Apparently, some work has been done and it would be awesome to see all that in a released package.
For example, #536 has been fixed quite some time ago but still hasn't reached any release version. "Official" workaround for this is to install `behave` from the current master which doesn't seem production safe to me.
Are there any reasons for this hold-up? Sorry if it was asked and answered before.

**Comment by samervin** [comment]
I'd like to second this. We're using and extending Behave in a internal environment. Installing packages that aren't properly published/versioned is a hassle. We're considering mirroring Behave internally just so that we can treat more recent versions as formal releases, but this introduces its own problems.

A release of 1.2.6 would lift a huge burden. cc @jenisys

**Comment by pauloxnet** [comment]
We're using behve from git too, please release 1.2.6 on pypi.

**Comment by Fandekasp** [comment]
Took me some time to figure out that `from behave import fixture` as described in the documentation would only work using the master branch.. Shouldn't the default documentation refer to the latest tag and not master ?

**Comment by pauloxnet** [comment]
@Fandekasp I think you can view docs for latest version (master) http://behave.readthedocs.io/en/latest/ and stabel versione (1.2.5) http://behave.readthedocs.io/en/stable/

**Comment by bittner** [comment]
@jenisys I think we should really discuss how we can make a faster, more regular release, in future.

That would also align with efforts of other projects, e.g. Pylint, who are [planning to release more often](https://github.com/PyCQA/pylint/blob/master/doc/release.txt).

**Comment by bittner** [comment]
Duplicates #587.

**Comment by jon-torodash** [comment]
Would it be so hard to cherry-pick the change made that fixed #536 and publish to pip without everything else planned for the typical release cycle? That seems to be most people's gripe.

**Comment by jenisys** [comment]
@jon-torodash 
Why should one cherry-pick when it is already integrated on the master branch for the next release?

**Comment by bittner** [comment]
@jenisys I think @jon-torodash believes that this would speed up the release process. Or would allow making a release possible at all.

Maybe you can share the reasons why a release is not happening for such a long time. And what we can help to make this happen.

**Comment by jon-torodash** [comment]
Yes, as @bittner remarked, I'd like to see a patch-level version bump to deal with this problem. Let me know if there is anything I can do to assist.

**Comment by dgommers** [comment]
Using Behave with PyCharm and Python 3.6 is quite a pain at the moment. I think it is very clear that there is a high demand for a new release from the community.

**Comment by jenisys** [comment]
@dgommers 
Which operating system? (Linux, macOS, Windows, ...)

OTHERWISE:
I am working on it. Windows has some Unicode issues what is currently blocking the release. 
If feasible, use a snapshot of the HEAD of github repository (master branch).

**Comment by jenisys** [comment]
DONE: Released behave-1.2.6 on pypi.

WARNING: 
On Windows, some unicode problems (and regression problems) still exist. I hope I will fix that soon.

**Comment by jon-torodash** [comment]
Thank you!

**Comment by dgommers** [comment]
Thanks @jenisys for the release! Works like a _charm_ on macOS 10.13 with PyCharm 2017.3 using Python 3.6.

**Comment by jenisys** [comment]
:smile:

**Comment by eserge** [comment]
Super! Thanks!

**Comment by bittner** [comment]
@jenisys Can we still discuss shorter release cycles? I've just [stumbled upon a comment](https://blog.jetbrains.com/pycharm/2017/06/upgrade-your-testing-with-behavior-driven-development/#comment-316439) that is a discouraging result of the few releases in the past few years. :worried: 

If this project sticked to [Semver](https://semver.org/) it should be feasible to do patch level releases ([as suggested by](https://github.com/behave/behave/issues/617#issuecomment-366680837) @jon-torodash above) for even small amounts of changes (fixes). This would be a huge step in terms of self-marketing. Let's talk! :mega:

**Comment by dmwyatt** [comment]
FWIW, I tried pushing through a switch to using behave in our internal testing environments and I was ultimately unsuccessful specifically because of this issue.

It was decided that we couldn't depend on and contribute to a project that has such large amounts of work "hidden" in the repo instead of pushed into official releases.  ☹️

**Comment by dmwyatt** [comment]
@jenisys Organizations have policies and hierarchies and lawyers and executives and legacy code and investors and hard-won organizational lessons. It is very common for organizations(1) to have a policy of only using official releases.  If work on a package is only available on HEAD it may as well not exist. And, unfortunately, the ability to fork and maintain a repo at a specific tag or something is often viewed as a bandaid for flawed management policies of the root repo.

What is important to _me_ is not really relevant.  *I like behave and advocated for it's usage in the organization I'm currently working with!*  I'll be done consulting for this place in a month and on to the next place.  It's nothing to me if they don't use this library.

I was trying to help behave by commenting about what is important to organizations in general. Most developers don't know (rightfully so) whats going on inside the collective "minds" of these organizations employing dozens, hundreds, thousands of developers.

For many devs and organizations, it is a code or management "smell" for there to be many months of commits without an official release.  It makes it look like the core devs are not paying attention. This holds whether or not the end user is some organization or some lone developer.  Like all "smells" it only is an _indicator_ of a _possible_ problem, but it's still a checkmark in the Negatives column.

@bittner's advocacy for shorter releases is _exactly_ the correct thing to do to address these concerns.  From an optics standpoint, it does not matter too much what the content of the commits in those releases is.  If I'm The Decider in some organization and paying a testing team of a dozen devs, I don't want to pay them to work on code that languishes un-released on someone else's repo for a year.

Not all organizations have a habit or policy of contributing code and other resources to the libraries they're using, and it's a pity.  But many do!  IMO, that's a crowd well worth chasing.

If the core devs view more contributing developers as a positive thing, then these are issues that have to be addressed.

I'm not sure why you brought up the fact that I, personally, have not contributed code to this repo.  I can only assume it was a misguided attempt to say something along the lines of "you can't make demands of us without providing any help yourself".  However, thats not where my comment was coming from. I was informing you of something you were potentially unaware of to help a library I like and use.  Code is only one of many important things a library needs to be successful. Management is just as important and my contribution to behave was insight into a potential use-case of the library.

If you don't care about what large potential users need, then that's perfectly fine.  I don't care, as I'll continue to use behave where appropriate in the projects where I have the power to decide.

(1) Often times this is a misguided policy, but as someone who has consulted for many large orgs on this topic and others...changing policy is hard.

**Comment by bittner** [comment]
> Organizations have policies and hierarchies and lawyers and executives and legacy code and investors and hard-won organizational lessons. It is very common for organizations(1) to have a policy of only using official releases. If work on a package is only available on HEAD it may as well not exist. And, unfortunately, the ability to fork and maintain a repo at a specific tag or something is often viewed as a bandaid for flawed management policies of the root repo.

@dmwyatt You sound quite frustrated. But there may be some misunderstanding on your side. Have you tried to install Behave via `pip install behave` (or `python3 -m pip install behave`)? This gives you the stable release. This release [does exist](https://pypi.org/project/behave/) and is fully functional. -- Is there a problem with that?

> I'm not sure why you brought up the fact that I, personally, have not contributed code to this repo.

I believe, @jenisys addresses your tone: If you have made substantial contributions you have the right to be heard when you're frustrated about maintainership, and harsh comments may be met with understanding. Otherwise, some respect for the people who have done all the hard work you can freely take advantage of should be assumed. Is this much to ask for?

> If you don't care about what large potential users need, then that's perfectly fine. I don't care, as I'll continue to use behave where appropriate in the projects where I have the power to decide.

Not sure what you're proposing. Is your organization offering to pay this Free Software project and needs securities for ongoing development? Who are you representing?

**Comment by jenisys** [comment]
@dmwyatt Thanks for your answers.
@bittner Thanks for interpreting my intentions right to the point.

As I already pointed out, we will try to release more often.

But this is an open source project. You get something "free" if you think it is worthwhile.
The project lives from the efforts of its maintainers (which have sometimes other things to do) and its committer that contribute to the project.

**Comment by dmwyatt** [comment]
Yeah, just to be double clear, I wasn't criticizing how the project was
run, I was providing more information to help decide where the limited
available resources should be "spent".

**Comment by xrg** [comment]
I would really love to read a technical discussion, solutions, rather than some long thread criticizing some open-source maintainer about the project's timeline. 
Don't get me wrong; I know what business want from software: commitment, continuity. And there's a gap between that and what can be delivered from people who won't ask anything in return of their effort. Both sides have to appreciate each other.
Open-source projects are no longer just 'fun'; they're used in real money-making cases. In that context, profitable businesses /should/ contribute back, donations or resources to keep projects rolling. On the other hand maintainers should lay a minimal roadmap, a "what to expect from this project" guide; and try to commit any resources to that, keep their audience alive.

**Comment by dmwyatt** [comment]
@xrg 
1. No one was criticizing anyone.
2. There is not really any technical discussion to be had in an issue about managing release schedules.
3. I agree with the rest of your comment.
