### ISSUE TITLE
Special Scenarios tags setup and teardown

### ISSUE THREAD

**Issue by pulphix** [behave/behave#637]
Good Morning,
I would like to understand if the tags @setup and @teardown are tags defined only on Behave or are tags that Cucumber Supports. I didn't find any reference on cucumber, raddish or behat.
Can you please provide me some information?

**Comment by jenisys** [comment]
This mechanism is currently only used in Behave (AFAIK). It helps if you want to use a Background/Scenario only once per feature for setup or teardown. It is mostly useful, if you use the file-location mechanism, like "features/my.feature:123". Scenarios marked w/ @setup are executed before the referenced scenario and Scenarios marked w/ teardown are executed after the referenced scenario.

NOTE:
* If you select-scenarios-by-tags thinks get more complicated because you need to include @setup/@teardown tags into your tag-expressions.
* There was a question/discussion with the Cucumber repository, if Feature-Background mechanism should be added to Gherkin. But that was rejected up to now.
