### ISSUE TITLE
run upon file change

### ISSUE THREAD

**Issue by dmvianna** [behave/behave#640]
Sorry if this is a dumb question, but what do you do to run `behave` automatically every time you make a change to a file in your project? I can't find a `--watch` option in the documents.

**Comment by xrg** [comment]
Behave is a "batch" runner: you'd provide it with a list of files and it would run them, in a single-shot. The runner also must "exit" somehow, in order to produce the resulting reports.
Therefore, I would suggest that you **wrap** the behave runner around some custom watcher, that would look for file changes (see python-inotify) and then just spawn a standard `behave` run.

**Comment by jenisys** [comment]
You can easily use [watchdog](https://pypi.python.org/pypi/watchdog) to monitor your feature directories and/or source directories and start to ``run behave`` when something changes. It is slightly more complicated when you want to run a minimal set go features for these changed files.

**Comment by dmvianna** [comment]
Do I really need to install more Python dependencies and then write configuration files and scripts for this to work? I would be happy if I could make
```bash
$ watch behave
```
give me coloured output. At the moment it gives me black and white regardless of me using `-c`. Should I be reporting it to you, Ubuntu or `watch`?
