### ISSUE TITLE
allure_behave formatter not showing the test case executions

### ISSUE THREAD

**Issue by senthilkumar369** [behave/behave#651]
Hi,

I am running my test cases using  allure_behave formater. for some reason, it is not showing the ran and running tested cases in  Command prompt when I am using " behave -f allure_behave.formatter:AllureFormatter -o allure-results test/Test1.feature". I can see the failed or total passed or failed once finished running it. I can see them if i run without allure formatter  "behave  test/Test1.feature"

Please fix it.

**Comment by jenisys** [comment]
Note if you are use ``behave -f my-formatter -o my-output ...`` you are writing the output of this formatter to a file. Why do you think it should output anything on the console ?!?

OTHERWISE:
Wrong repository, contact the maintainer of the [allure-behave formatter](https://pypi.org/project/allure-behave) or https://github.com/allure-framework/allure-python .
