### ISSUE TITLE
HOOK-ERROR indication in test report

### ISSUE THREAD

**Issue by BNMetrics** [behave/behave#688]
When there is a failure in setup process: `before_all`, there is no indication of failure in the test report. 
It would be nice if there is an option to catch these `HOOK-ERRORs` in the xml test report.  Or to have an option such as `contest.fail_all()` to fail all the subsequent tests if `HOOK-ERRORs` were to appear.

**Comment by jenisys** [comment]
Mmh, I disagree. Either you are seeing some else or ...
Are you using the newest, released version (1.2.6) ?

If the `before_all()` hook fails, you get an error message `HOOK-ERROR in before_all(): ...`. All tests are failed because they are **untested**. This is normal when a fatal error like that occurs and aborts the test run.

SEE ALSO:
* `Scenario: Hook error in before_all` in [features/runner.hook_errors.feature](https://github.com/behave/behave/blob/master/features/runner.hook_errors.feature#L119)

**Comment by BNMetrics** [comment]
Hi @jenisys,
Sorry for the confusion, and I probably should have made myself a bit more clear.

Yes, I do get the `HOOK-ERROR` as an output in the terminal, however, this error message is only printed as a string to the terminal(as seen in `behave/runner.py, ModelRunner.run_hook`). This is all fine if I'm running the tests locally.

It would be a problem if I'm to run the tests in a CI/CD pipeline, skipped tests could be considered as `passed` because sometimes I could have tests to skip on purpose. If I were to use the junit report file to analyse the test status, there isn't anyway I can know if it's a failure on the setup either. This could potentially be a red herring.

**Comment by jenisys** [comment]
NO PROBLEMS ARE:
- [x] Each CI/CD tool that I know can use the result code of a command and indicate if the command has failed or not. Therefore, this is not a problem (IMHO).
- [x] Each CI/CD tool has a console log. Therefore, the HOOK-ERROR appears there.

I agree that it would be nice to have the hook errors in your test report (from JUnit XML, etc.).
But that requires the hook errors are captured (which is planned but needs some kind of infrastructure). An easy way would be to report the number of `hook_failures` in the SummaryReporter because this information is already tracked in the test runner.

@BNMetrics Change the title of issue accordingly (whatever your main intention is).

**Comment by BNMetrics** [comment]
@jenisys 
HOOK-ERRORs can appear in console log in a CI/CD tool, however from what I have seen, the test run can still be green, and the failure could be easily missed unless we go in the console log.

```
An easy way would be to report the number of hook_failures in the SummaryReporter because this information is already tracked in the test runner.
```
That's exactly what I was thinking as well.

I have changed the title now, and yes, my intention is to have hook-errors reported in the test report files.

**Comment by fenwickipedia** [comment]
Hi, is there any update on the change to better report these hook failures? Indeed we have missed these in CI/CD tests where all tests are reported as pass. Just recently with Behave v1.2.6. Would be really helpful to have this fix. Also, shouldn't the exit code be non-zero? Thank you.

```
HOOK-ERROR in before_all: KeyError: 'hooks_test_api'
HOOK-ERROR in after_all: AttributeError: 'NoneType' object has no attribute 'clear_cache'

ABORTED: By user.
0 features passed, 1 failed, 0 skipped, 21 untested
0 scenarios passed, 0 failed, 0 skipped, 200 untested
0 steps passed, 0 failed, 0 skipped, 0 undefined, 2698 untested
Took 0m0.000s

Process finished with exit code 0
```

**Comment by jenisys** [comment]
@fenwickipedia 
Mmh, weird. I see one things in your console output example that makes me wonder:

* The final line "Process finished with exit code 0" is not from `behave`
* `behave` hook-errors cause a non-zero exit code

QUESTION:
Are you really sure that the `exit code 0` is from `behave` and not from a tiny shell script that overlooked the non-zero exit code (category: user-error) ?

SEE ALSO:
* [features/runner.hook_errors.feature](https://github.com/behave/behave/blob/master/features/runner.hook_errors.feature)

**Comment by jud55555** [comment]
> Hi, is there any update on the change to better report these hook failures? Indeed we have missed these in CI/CD tests where all tests are reported as pass. Just recently with Behave v1.2.6. Would be really helpful to have this fix. Also, shouldn't the exit code be non-zero? Thank you.
> 
> ```
> HOOK-ERROR in before_all: KeyError: 'hooks_test_api'
> HOOK-ERROR in after_all: AttributeError: 'NoneType' object has no attribute 'clear_cache'
> 
> ABORTED: By user.
> 0 features passed, 1 failed, 0 skipped, 21 untested
> 0 scenarios passed, 0 failed, 0 skipped, 200 untested
> 0 steps passed, 0 failed, 0 skipped, 0 undefined, 2698 untested
> Took 0m0.000s
> 
> Process finished with exit code 0
> ```

This happened to me two days ago for guys who will still visit this issue. It was because if of the calls, I was calling an envirnoment variable in the python code (using os.getenv("SOME_ENV")), but my IDE was not started from were I had this SOME_ENV set (in $HOME/.bashrc), so I just put it in $HOME/.profile, SOME_ENV being visible by the whole system. You could also start pycharm with a container with SOME_ENV set.
Reason for all of that is if SOME_ENV = "", os.getenv() and what comes after return NoneType to function called in my case.

**Comment by jenisys** [comment]
@jud55555 
Behave uses non-zero exit codes if a problem occurred (including hook errors).
Are you using the official behave runner or your own script ?

SEE ALSO:
* [features/runner.hook_errors.feature](https://github.com/behave/behave/blob/master/features/runner.hook_errors.feature)

**Comment by ckasyapa** [comment]
HOOK-ERROR in before_all:NoSectionError : No Section: 'general' though i do not have any file general

**Comment by JSorella** [comment]
Hi, I would like to re-open this discussion.
I have the same issue as @BNMetrics and @twfenwick mentioned before.

In my CI/CD Job (Jenkins) I see all tests marked as PASSED because Behave marks tests with HOOK-ERROR as "Skipped".
If all tests are marked as "skipped", then the CI/CD will take this as a PASSED execution.
I would like to understand how to catch/handle HOOK-ERRORs as failed tests.

**Comment by jenisys** [comment]
@JSOrella
That is clearly not true (that `behave` marks HOOK-ERRORS as `skipped`).
Otherwise, the feature tests to this functionality would not pass.

* Provide a minimal example where that is the case

SEE ALSO:

* [features/runner.hook_errors.feature](https://github.com/behave/behave/blob/main/features/runner.hook_errors.feature)
