### ISSUE TITLE
Scenario Outline with no examples are not picked up

### ISSUE THREAD

**Issue by apchew** [behave/behave#689]
I wrote a scenario outline with brand new steps without any step definitions. I expected some indication that the steps were undefined or skipped but behave just showed that the feature passed.
```
Feature: Testing
  
  Scenario Outline: Test 1
    Given service is healthy
    When I kick it
    Then the service dies
```

```
1 feature passed, 0 failed, 0 skipped
0 scenarios passed, 0 failed, 0 skipped
0 steps passed, 0 failed, 0 skipped, 0 undefined
```
Is this intended?

**Comment by jenisys** [comment]
The ``Scenario Outline`` is a template with placeholders.
The ``Scenario Outline`` as template is used to generate ``Scenario``(s) from it,
one ``Scenario`` per ``Examples`` table row with the placeholders the columns this row.

**HINT: You forgot the ``Examples`` table. Therefore, this ``Feature`` has no scenarios.**

Either:
* Use ``Scenario`` instead of ``Scenario Outline`` or
* Use ``Scenario Outline`` with placeholders and ``Examples`` table

(what ever your intention was).

**Comment by apchew** [comment]
Ok, thanks
