### ISSUE TITLE
How to Debug behave test in VSCode

### ISSUE THREAD

**Issue by jpatel13** [behave/behave#709]
As per the title I would like to know how VSCode can be setup so that I can debug my Behave tests. 

Thanks!

**Comment by jenisys** [comment]
As with every IDE:

1. Learn how debug a python script / python module (by setting breakpoints) with your IDE
2. Use installed “behave” script or provide an own  “my_behave.py”, like:

```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# ASSUMPTION: behave is installed.

import sys
from behave.__main__ import main as behave_main

if __name__ == "__main__”:
    sys.exit(behave_main())
```

and run it from the IDE with the debugger.

**Comment by acaciomartins** [comment]
Beautiful solution! Tks very much... :)

**Comment by valhuber** [comment]
Many thanks for this, very much needed.

As shown below (here is [full git project](https://github.com/valhuber/TDD#readme)), my attempt fails on import.  I am guessing this is because I pip'd `behave`, without installing source.  Is there a procedure for pip'd `behave`?

Thanks in advance,
Val

<img width="1348" alt="debug-my-behave" src="https://user-images.githubusercontent.com/5579631/157907331-583e461a-40c3-4a23-803f-49898be8c988.png">

**Comment by jenisys** [comment]
I assume you have one of the following problems:

* P1: You may have installed `behave` into another Python interpreter on your computer (not the one that you are using in VSCode and the was installed with `homebrew`)
* P2: You may have caused module namespace pollution with `test/behave/ `

## CASE P1

CHECKS:

* Start your Python interpreter in a terminal/shell
* Inspect `sys.path` if it is the same one (as in the screenshot above)
* Try: `import behave`
* If `behave` can be imported, your `pip3 install behave` installation should be OK.
* If `behave` cannot be imported, use `pip3 install behave` to install it.
  HINT: Verify that `pip3` belongs to your Python interpreter by using: `pip3 --version` (it will show the pip version and the Python version)

## CASE P2

* EXPERIMENT: Rename `test/behave` to `test/behave2`
* If the problem goes away, you should try to avoid to providing your own `behave` package that overshadows the original `behave` package.
* HINT: This case is not very likely (because Python3 uses absolute-imports), but verify it.

OTHERWISE:
* Your problem does not look like a `behave` problem.
* You should not reopen closed issues with additional (related) stuff but slightly other context. Open a new one, if it is a bug or a feature request.
* Use an issue in the `Discussion` tab above for asking questions (like this one).

SEE ALSO:
* https://github.com/behave/behave/discussions

**Comment by valhuber** [comment]
Thanks @jenisys - working perfectly now...

It was P2 -- avoid `behave` package names!
