### ISSUE TITLE
How to explicitly fail test?

### ISSUE THREAD

**Issue by jyoung9028** [behave/behave#715]
So I've been using behave for a bit and sometimes, I want to explicitly fail a test if a certain thing happens. The way that I have been handling it was to explicitly raise an Exception. However, I have run into an issue where that is not failing the feature file that contains a Scenario Outline. It only fails that specific run of the Outline. It then tries to continue on.

Is there a way to force fail a test that I'm overlooking?

**Comment by jenisys** [comment]
Yes, the obvious (as expected) :wink:

How about:

```
@step(u'I do something and it always fails')
def step_I_do_something_and_it_always_fails(context):
    do_something(...)
    assert False, "ALWAYS FAILS HERE" #< -- FAIL-TEST-IDIOM
```

Otherwise:

* Raise AssertationError() exception
* Raise KeyboardInterrupt() exception to abort the test-run

SEE ALSO:

* [features/runner.stop_after_failure.feature](https://github.com/behave/behave/blob/master/features/runner.stop_after_failure.feature)
* [features/runner.abort_by_user.feature](https://github.com/behave/behave/blob/master/features/runner.abort_by_user.feature)

**Comment by jyoung9028** [comment]
I already tried that. It was only in Scenario Outline's that the failures were not happening. I figured it out though. It was a gross oversight by me. It was correctly failing the scenario; however, it wasn't failing the feature. Which is what I wanted to do. Because technically, an outline is just a bunch of scenarios, it was working correctly. I had to change the configuration of behave to fail an entire feature file on failure. The default setting is for it to not too.

Thank you for your help though!

**Comment by jenisys** [comment]
Sorry, but any failed Scenario even from a Scenario Outline causes urs Festure to fail.

**Comment by jyoung9028** [comment]
That has not been my experience. By default - the setting to do that is set to false.

**Comment by yonraf** [comment]
@Duroxxigar Could you please share how u solved it? I find no solution to this out there, but u seemed to crack the code
