### ISSUE TITLE
Auto Complete within context

### ISSUE THREAD

**Issue by Duroxxigar** [behave/behave#717]
Thought I could ask here and see if anyone else is experiencing this. I currently have some objects created and stored in my context variable in the before_all hook. When I go to write the steps, and try to use those objects, I do not have intellisense. Not sure if this is how it is supposed to be or not though. Only one of my stored objects have intellisense, so that is weird.

I have tried googling around and haven't seen anything about it. As well as asking around in the Reddit and Discord Python communities. I have used PyCharm and VSCode. Both do not provide intellisense for my created objects inside of the context variable. Any thoughts?

**Comment by jenisys** [comment]
This is more or less and IDE problem and not a behave problem.

The adding of attributes to the `Context` objects are "movements in time".
Because your step-function does not know what was executed before, it can only resolve `static attributes` that are allocated the `Context` class and not during runtime of the behave test-runner.
