### ISSUE TITLE
Enhancement: Context.add_cleanup() with layer-name (can choose outer layer)

### ISSUE THREAD

**Issue by nizwiz** [behave/behave#740]
It would be nice to be able to have a variant of add_cleanup with which you could specify upon which context stack frame exit to call the cleanup function, so that it is possible during execution of a scenario to add a cleanup which is to be called after the whole feature is done.

**Comment by jenisys** [comment]
I had this implementation already, but removed it. By using fixtures and fixture-tags, you have normally easier control to what you want to do at the right cleanup-level.

I assume that you add or need to add the cleanup function in a step ?!?

**Comment by nizwiz** [comment]
I was actually trying to avoid using fixtures. No offense, but IMO it's not a good concept. Gherkin is designed in such a way that the information should be written in natural language to be easily readible, even by people who do not have a backround in programming / software testing. Also, Gherkin features should be independent of the used famework: One should be able to switch out the implementation layer without having to adapt the Gherkin features - e.g. switching from python/behave to C#/SpecFlow etc.
The fixture tags are extending the Gherkin language by proprietray stuff, and in a way which contradicts Gherkin's design priciples.

**Comment by dcvmoole** [comment]
(Seeing as I am hesitant to open a new issue for the same basic suggestion, I can merely hope that this comment gets read at all! In any case:) I too would very much appreciate the feature suggested here.

I feel like this thread is missing a concrete use case so far, so please allow me to sketch mine. I am working on an add-on module for a family of larger (company-internal) projects that all use (and set up) Behave in slightly different ways. My add-on module provides its own Behave step definitions, for use in the larger projects' feature files. The idea is that the larger project uses a "stub" steps file that basically contains only `from my_addon.behave.steps import *`, thus making available all of the add-on's Behave steps in that larger project. That works well, and that stub file is easy to add to any of those projects. So far so good.

However, my add-on module requires setting up one or more sessions to remote resources (basically, lab equipment), and it does that whenever one of the add-on's 'Given'-steps is used (based on certain step-provided parameters). The scope of those sessions is the feature level: they should be cleaned up automatically at the end of the feature file, and only then. Thus, my add-on needs to be able to perform a clean-up action at the end of the feature, for a session object that was set up from a step. Therefore, the current add_cleanup() is not sufficient for this case.

What I basically would like to avoid, is to require the maintainers of the larger projects to add a call from their environment.py's after_feature() into my add-on module to perform the clean-up, because that would seriously take away from the "drop-in" nature of my add-on -- _much_ more so than the need to add the stub steps file. I believe that for the same reason, fixtures would not help me here: those would require explicit changes within the environment.py of the larger project as well (but, there are other reasons that fixtures are not a good fit for my case). Getting such a clean-up call added once is not the end of the world, but we'll likely want to make more, similar add-ons, each of which would then need their own environment.py additions in the various larger projects. Maintenance-wise, I think that just does not scale well.

I believe the original poster's suggestion would cleanly and fully resolve that problem, and with that, perhaps even help a little in allowing Behave to support such "modular" approaches to adding steps from add-ons in general..? Ultimately it's a small issue, but it is one that bugs me a bit, because with the current add_cleanup(), Behave is already _so_ close to offering what I'd need! FWIW, I'd be happy to take a shot at contributing code for this, but if you already had this implemented at some point, you will have a much better idea of what you'd want it to look like..

**Comment by jenisys** [comment]
I see your point.

BUT: Is the post-poned cleanup really enough for your use case?
Everything else that you have stored in the given step, is removed when the Scenario finishes (and its context layer is popped). If you still need to have access to your resource objects (session object, database connection, etc.), you need to store them outside of the context (and restore them later at the begin of the next scenario where it is used).

**Comment by dcvmoole** [comment]
> BUT: Is the post-poned cleanup really enough for your use case?

It is, yes. So far, my add-on module has simply been storing its state in a module-private global variable. Not the neatest solution perhaps, but given that only one feature is being run at once anyway, it is good enough. With such a global variable, all that is needed is the trigger for the clean-up.

Storing the state in the context would definitely be nicer, but I believe that would indeed require an additional enhancement, namely the ability to assign a variable at a context layer other than the top one. I'd imagine it could be possible to add some sort of get_parent_layer() method to Context, which returns a "pseudo-context" object with read-write access to that parent layer's variables, as well as with add_cleanup() and get_parent_layer() methods on it -- or something like that. But, I don't know if that is a good idea in theory, nor how difficult it would be to implement in practice. It is a bit more than the minimum that I'd need for my use case, but it _would_ allow me to get rid of the global variable..

**Comment by jenisys** [comment]
INTEGRATED INTO: behave-1.2.7.dev2
