### ISSUE TITLE
Stack trace for failing steps

### ISSUE THREAD

**Issue by retorquere** [behave/behave#743]
I have an error somewhere in my before_all, but behave doesn't give me the stack trace, I just get 

```
HOOK-ERROR in before_all: FileNotFoundError: [Errno 2] No such file or directory: '/Users/emile/.BBTZ5TEST.log'
```

Is there a way to get behave to give me the stack trace? Without it it's very hard to debug the steps.

**Comment by jenisys** [comment]
The problem is in the "environment.py" file in the ``before_all()`` hook implementation.
Use the `--verbose` option to enable stack traces for hook-errors, like:

```sh
$ behave --verbose features/
...
HOOK-ERROR in before_all: RuntimeError: FAIL
  File "/.../behave/runner.py", line 549, in run_hook
    self.hooks[name](context, *args)
  File "features/environment.py", line 9, in before_all
    cause_hook_to_fail()
  File "features/environment.py", line 4, in cause_hook_to_fail
    raise RuntimeError("FAIL")
called_hook:after_all

ABORTED: By user.
...
```

HINT: Stack traces are shown for step implementations.

**Comment by ns-cweber** [comment]
Why are stack traces suppressed at all? What is the use case? It makes it hard and frustrating for developers in our organization to debug issues, and consequently (not solely due to this particular issue) developers have a negative opinion of behave in general--it's hard to get buy in to use it more, and developers end up writing their tests with pytest rather than behave.

**Comment by jenisys** [comment]
@ns-cweber
Mmh, you seem to be dealing with only one stakeholder role/persona.
As always, there is a trade-off:

* Do you want to have simple, understandable failure/error line (one line) ?
* Do you always be cluttered by 40 lines of traceback (many lines where you first need to gain the understanding what has happened) ?

OTHERWISE:

* Hook failures/errors are a special beast (especially for: `before_all()`)
* Why do want to see the traceback for a KeyboardInterrupt exception (the user just wants to abort the program) ?
* As described above, you can tweak the behaviour to your needs / likings (for example also in the `before_all()` hook.

**Comment by ns-cweber** [comment]
@jenisys I agree that it's configurable, but that's a small consolation to developers who don't understand behave and just need to reproduce some issue locally that they're seeing in CI. They now need to study behave's configuration options to figure out how to turn on stack traces, and it makes them frustrated (perhaps they oughtn't be, but I find it better to deal with the world as it is rather than as it should be). This is just feedback; if you care about buy-in from developers, our experience suggests that better defaults (and considering this persona) might facilitate (and it probably won't hurt other personas at all).

In general, I don't think the short snippet has ever been sufficient for me, so any persona that needs to debug pretty much needs that, and I'd rather deal with seeing the KeyboardInterrupt exception (if it's too much to ask for behave to special-case that exception) than not have the information I need.

**Comment by sorgloomer** [comment]
I would also like to add that `ExceptionUtils.describe` does not traverse the `__cause__` chain of the exception, so even specifying `--verbose` won't give us all the information that `traceback.print_exception` does
