### ISSUE TITLE
What are the extensions to enhance Behave?

### ISSUE THREAD

**Issue by alexdesignworks** [behave/behave#752]
Apologies for the noob question.

I'm new to python world coming from PHP.

In PHP we have Behat which has a lot of extensions available to work with HTML (asserting for element presence etc).

Are there any extensions like this for Behave? I want to test UI by loading pages and asserting element presence (also following links).

Thank you

**Comment by dunossauro** [comment]
@alexdesignworks you are using selenium?

**Comment by jenisys** [comment]
My best guess is to look on pypi or github.

HTML related functionality should normally have nothing to do with behave.
[Python standard library](https://docs.python.org/3/py-modindex.html), [requests](https://behave.readthedocs.io/en/latest/behave_ecosystem.html), [Selenium](https://pypi.org/project/selenium/), [BeautifulSoup](https://pypi.org/project/beautifulsoup4/), ... whatever helps you in your problem domain.

OTHERWISE: behave related
* https://behave.readthedocs.io/en/latest/behave_ecosystem.html

**Comment by alexdesignworks** [comment]
Thank you replying.

I've spent some time on the investigation of possibilities and ended up using Behave + Behaving + Chrome (in Docker container).

This is how it works:

We are using [Behave](https://github.com/behave/behave) BDD _framework_ with additional _step definitions_ provided by [Behaving](https://github.com/ggozad/behaving) library.

Custom steps described in `test/features/steps/steps.py`.

Test scenarios located in `test/features/*.feature` files.

Test environment configuration is located in `test/features/environment.py` and is setup to connect to a remote Chrome instance running in a separate Docker container. 

During the test, Behaving passes connection information to [Splinter](https://github.com/cobrateam/splinter) which instantiates WebDriver object and establishes connection with Chrome instance. All further communications with Chrome 
are handled through this driver, but in a developer-friendly way.

For a list of supported step-definitions, see https://github.com/ggozad/behaving#behavingweb-supported-matcherssteps.
