### ISSUE TITLE
tags for steps

### ISSUE THREAD

**Issue by SempaiPrague** [behave/behave#754]
As I understood from the documentation, tags only work on feature or scenario level. 
It would be nice if you can create specific tags for steps as well. 
Could this become a new feature in the future?

Because I have the case where I want certain steps to still fail, but not to stop the scenario run.
There is the option Scenario.continue_after_failed_step, but this by default applies to all steps in that scenario, which is unwanted. 
Or does there exist a current method to still fail specific steps, but not let it interrupt the scenario? (without applying to all the steps in that said scenario)

Much appreciated.

**Comment by lawnmowerlatte** [comment]
What is the use case for this, why do you need to finish the scenario if the step fails? If it's to do something like teardown of an environment you might want to add some `after_scenario` hook integration to ensure some cleanup is done.

**Comment by dunossauro** [comment]
That smells bad to me. If you want to check the condition you can use after_step.

Maybe you can use something like:

```Python
def after_step(context, step):
    if step.name == "my step":
        ...
```

IMO tags for steps is insane, cause if you put many tags?


```feature
Feature: Test
  Scenario: blah
    @tag_A
    Given given
    @tag_B
    And another given
    @tag_C
    Then then that
```
In this case, the purpose of BDD is broken,  cause the executable documentation doesn't represent how exactly the thing is happening. Creates a new gap in communication.

**Comment by dunossauro** [comment]
@SempaiPrague 

Did you saw the gherkin v6?

Maybe can help you.

```feature
Feature: Test
  Rule: Rule_1
    Background: background for rule
      Given given

    Example: example_1
      Background: Background for example
        Given given_2
        Then then
```

In this case you can create two backgrounds

**Comment by jenisys** [comment]
@SempaiPrague 
Tags for steps will never happen IMHO.

Reasons:
* Gherkin documents `*.feature` should be readable and understandable
* Tags for steps introduces a lot of noise and would make the feature file unreadable
* You are trying to solve the wrong problem IMHO
* A Scenario is the smallest unit where you can use tags to run it or not
* A Scenario makes only sense if all steps are executed and pass
* Otherwise you are tying to solve problems in a flake environment
  SOLUTION: Make your test environment not flake (failing every now and then).

Otherwise, from your description you need to make your hands dirty.
I still do not see why you need it and what are your "pain points".
My best guess is:
* you need the "continue after failed step mode"
* Need some implementation for the `after_step()` / `after_scenario()` hook to provide the correct behaviour for you
* Revert the `Scenario.continue_after_failed_step = True` to `False` in the hooks if needed

**Comment by jenisys** [comment]
Without quite knowing all details, I would provide the core functionality with a specific fixture.
The fixture is only provided when its fixture-tag is used (on specific Scenarios, Features, ...).
That allows you at least some control, when the real work for you needs to be done.

And you may need something like a test (or step) oracle that can be asked if this step is allowed to fail or not.

**Comment by SempaiPrague** [comment]
Thank you all for your input.
It does seem a bit over the top after all, to introduce step-tags.

Ill see to change my core-functionality to be more robust.
