### ISSUE TITLE
Do not execute background before scenario

### ISSUE THREAD

**Issue by Mina05** [behave/behave#756]
Hi,

I'm searching a way to avoid the background running before a scenario. My scenario is looking like the below code. I found [this](https://stackoverflow.com/questions/41637534/how-to-skip-steps-in-background-of-behave-bdd) but collecting everything in one step is not that what I need.

```gherkin
Background:
  Given I visit a page
  And I do something special for this feature

@no_background
Scenario: no need for background because doing something else
    Given I visit another page
    And I want to configure something
```

If it's not possible to skip the whole background then I would need a solution to overwrite the background. I also tried to start writing a fixture for

```python
def before_tag(context, tag):
    if tag =="no_background":
        use_fixture(execute_no_background, context)
```

but I could not find out how to disable/override the background.

I hope someone can help me here.

**Comment by jenisys** [comment]
The "Background" concept is a tool in Gherkin.
And you seem to be fighting it and I am not quite sure why.
This could be:

* a conceptual problem how to structure things in Gherkin or 
* a development issue that you temporarily want to have things differently while running / testing the Feature files.

The following advices are related to the first point (structuring things in Gherkin and below).

The Background concept allows you to specify the common steps in a Feature to avoid replicating them in all Scenarios. If you do not need the Background steps for all Scenarios, then the Background steps are not "Common initial steps". Therefore, you have two solutions:

* Remove the Background in this Feature and move the Background steps to the Scenarios were they are needed (causing some replication). Other Scenarios that do not need the Background steps initialisation / setup / preparation are fine (may cause a problem when your are running only one Scenario instead of all Scenarios of this Feature).

* Split-up the Feature file in two (or more) Feature files, one with the Background and one (or more) without it, like: FeatureA.common.feature, FeatureA.aspect_2.feature, ... (SOLUTION_2)

* Provide the Background steps as one "composite step" that uses `ctx.execute_steps()`. This allows to to use the composite setup step where needed.

* Move the setup concepts even more down in the step implementations (or below). The step implementations ensure that a certain setup is performed before they do their work. If this setup was already done, nothing needs to be done. This could be solved by using fixture(s) or other RAII concepts. 

HINT:
The `@no_background` solution above is a HACK. You would basically need to remove the reference to the Background (and/or the copy of the Background steps) in the Scenario before it is executed.
SOLUTION_2 is probably the better / easier way.

**Comment by jenisys** [comment]
PROOF-OF-CONCEPT source code (and I am not saying you should use this).

```python
# -- HINT: @fixture.behave.override_background = @no_background (from above)
from behave import fixture

@fixture(name="fixture.behave.override_background")
def behave_override_background(ctx):
    # -- SETUP-PART-ONLY: Disable background inheritance (for scenarios only).
    current_scenario = ctx.scenario
    if current_scenario:
        behave_disable_background_inheritance_for_scenario(current_scenario)


def behave_disable_background_inheritance_for_scenario(scenario):
    print("FIXTURE-HINT: DISABLE-BACKGROUND FOR: %s" % scenario.name)
    scenario.background = None
```

**Comment by jenisys** [comment]
Aah, and there is another solution as soon as the new behave version is released.
You can group scenarios with multiple Rules, each having its own Background (as long as you do not use the Feature Background). Basically like SOLUTION_2 from above but all in one file.

SEE ALSO:
* [behave.docs: Latest changes -- Gherkin v6 Grammar](https://behave.readthedocs.io/en/latest/new_and_noteworthy_v1.2.7.html#support-gherkin-v6-grammar)

**Comment by Mina05** [comment]
Thank you so much!
The reason why I have to do this is because I need to visit two different pages but mostly I visit page A and do some general things (what I need for the most scenarios). But then somewhere between these scenarios in the same feature file I had to visit another page B and I don't wanted to wait for the background steps.
