### ISSUE TITLE
master at 1.2.7 is incompatible with python2.7

### ISSUE THREAD

**Issue by xrg** [behave/behave#757]
I noticed that as of tag 1.2.7dev1, the source is no longer compatible with python2.7
I see the arguments about python2 becoming obsoleted etc.
However, dropping support for the language is a big step, cannot go under a minor version.

Please release next version as 1.3.0 or something. Not in the 1.2.x series, that had python2.7 compatibility.

**Comment by jenisys** [comment]
@xrg
This is a Python2.7 hint, not a behave issue.
Every package that is installed with `pip` for Python 2.7 gets this hint that Python 2.7 support will end at the beginning of year 2020.

**Comment by xrg** [comment]
You are still changing the requirements (+ syntax) in your project. This classifies for a middle version number, it is breaking backwards compatibility.

**Comment by jenisys** [comment]
@xrg @ThrawnCA 
Mmh, interesting.
Expectation management at its best:

* Where is it written that this repo follows „semantic versioning rules“ ?
* Where is it written that all projects from the beginning of time use and have used semantic versioning ?
* Publishing `v1.2.7.x` as `v1.3.0` a way into the direction of semantic versioning ?!

**Comment by jenisys** [comment]
Expectation management at its best:

* Shows me the line where this repo states that it follows semantic versioning rules ?
* You because you think every project should use semantic versioning rules, does not mean than every project does that.
* And not every project since the beginning of time has used semantic versioning rules.
