### ISSUE TITLE
Fix docs about rule and Background

### ISSUE THREAD

**Issue by edusantana** [behave/behave#770]
From [https://cucumber.io/docs/gherkin/reference/](https://cucumber.io/docs/gherkin/reference/):

> The (optional) Rule keyword has been added in Gherkin v6. (Note that Gherkin 6 has not yet been incorporated into all implementation of Cucumber!) The purpose of the Rule keyword is to represent one business rule that should be implemented. It provides additional information for a feature. A Rule is used to group together several scenarios that belong to this business rule. A Rule should contain one or more scenarios that illustrate the particular rule. **A Rule cannot contain a Background**.

And the [website](https://behave.readthedocs.io/en/latest/new_and_noteworthy_v1.2.7.html):

![rule](https://user-images.githubusercontent.com/3603111/62469198-25349780-b76e-11e9-9461-1b06aa261bc3.png)

I may be wrong...

**Comment by jenisys** [comment]
The removal of Backgrounds from Rules in Gherkin v6 is rather new.
The original part of this text contained the Background element (and I know that because I wrote that part). The current HEAD of the behave implementation supports **Rule Backgrounds**. Currently, I plan to support them for the next future (as a extension the Gherkin v6 grammar). But you do not have to use them.

**Comment by edusantana** [comment]
@jenisys I use "Scenario Outline" inside "Rule". For me it's ok to only have one Background. It's nicier to read like this.

**Comment by edusantana** [comment]
@jenisys I can create a real example to put there, would you like this kind of contribution?

**Comment by NoiseByNorthwest** [comment]
It totally agree with @jenisys, as long as it is clear in the documentation that Rule Backgrounds is an extension.
