### ISSUE TITLE
French given step is not fully supported

### ISSUE THREAD

**Issue by zadigus** [behave/behave#777]
Hi, 

I'm using behave version 1.2.6 and write my Gherkin specification in French. I assumed that the [Gherkin reference](https://cucumber.io/docs/gherkin/reference/#overview) was the reference for behave too, but apparently not completely. For example, the following step 
```
Etant donné qu'il est entré dans un Shop
```
results in the following step skeleton proposition
```
You can implement step definitions for undefined steps with these snippets:

@given(u'qu\'il est entré dans un Shop')
def step_impl(context):
    raise NotImplementedError(u'STEP: Given qu\'il est entré dans un Shop')
```
In particular, you can see that the string "qu\'" is part of the argument to `given`, which should not be the case. Is that intended?

**Comment by wimo7083** [comment]
I am not a french speaker nor a maintainer, but I think your problem is that you're suggesting that you want `Etant donné qu'il` be the step  type identifier. 


It looks like there are [many ways](https://github.com/behave/behave/blob/67e54d5535944c851c506b9ed31dbafb2e339497/behave/i18n.py#L383) of saying "given" in french.  

If `Etant donné qu'il` is another one I'd recommend you submit a pull request to correct this. 

If this is not what you mean maybe clarify it a bit more?

**Comment by wimo7083** [comment]
It looks like the official gherkin reference has more ways of given than are supported here:
https://cucumber.io/docs/gherkin/reference/#overview

**Comment by zadigus** [comment]
@wimo7083 interestingly, the way I am suggesting in this issue, `Etant donné qu'`, is part of the list provided [here](https://github.com/behave/behave/blob/67e54d5535944c851c506b9ed31dbafb2e339497/behave/i18n.py#L389). However, it is not working.

**Comment by jenisys** [comment]
Try to reverify your problem with the current HEAD of the Github repository.
The I18N implementation changed and the new one probably solves your problem.

HINT: 
* The parser implementation in behave-1.2.6 assumes that the step-keyword ends with whitespace character which is not the case in your example.
* Your link from above points to the current HEAD (if I am not wrong)

**Comment by jenisys** [comment]
Closed due to inactivity.
