### ISSUE TITLE
How to configure celery in behave tests?

### ISSUE THREAD

**Issue by gauravt1** [behave/behave#796]
Right now, I am using `celery_always_eager=True` in environment.py file, which is just executing an asynchronous celery task like a function, but I got stuck at an API where we are doing some thing like below - 

```
def active_status(self, request, pk):
    obj = get_object_or_404(queryset, pk)
    obj.active = True
    obj.save()
    end_date_time = 5(sec)
    #......
    #......
    deactive_status.apply_async(kwargs=obj.__dict__, eta=end_date_time)
```
`deactive_status` is a celery task which update the status of object `obj` back to `False` after duration specified in `end_date_time`.

But right now due to `celery_alwasy_eager=True` setting it just picks that task and execute it right away without considering the delay duration.

I thought there must be some way to configure celery in behave but not sure how it gonna accomplished, I didn't found something similar in their docs as well as other available resources.

If anybody have any idea about the same or something similar that would be really helpful. Thanks!

**Comment by jenisys** [comment]
Looks like a task for a fixture.
It sets up celery to your needs and tears the configuration down (`deactivate()`) when you leave the scope (scenario, feature, ...).

HINT: 
* You can also inject the fixture within a (setup) step by using `use_fixture()`.
* As already answered on the Gitter channel.

**Comment by Gaurav-t** [comment]
but it's an api which I mentioned above. You mean I need to test the celery stuff individually using fixtures?

Celery runs in a a different shell/ in daemon mode. do I need to produce the same kind of env in feature tests setup phase?

**Comment by jenisys** [comment]
Mmh, I am not a Celery user. I just looked at it a few times.
From my point of view you need to set something up before you use it (and maybe afterwards need to clean it up later). This is the normal use case of a fixture in Behave.

**BUT:** If you read the Celery documentation, your `deactivate_status.apply_async(...)` is executed synchronously at not asynchronously because you are using `celery_always_eager = True` (if I understand the docs correctly).

SEE:
https://docs.celeryproject.org/en/latest/userguide/configuration.html#std:setting-task_always_eager

HINTS:
* You have a Celery setup problem and not a Behave problem (IMHO)
* Behave normally executes steps synchronously. Otherwise, you do not know if an executed step has succeeded or not
* Behave has support for testing async steps (look it up in the docs if that makes it simpler for you). But at latest at the end of a Scenario all async operations should be completed (independent of some pending async cleanup tasks).

RELATED (and similar):
* https://github.com/RentMethod/celerytest

This should be similar to your problem w/ an example w/ Lettuce instead of Behave.
The setup/teardown part (@before.harvest and @after.harvest should be placed into your fixture implementation). The fixture is more flexible that the before/after hooks (but you can also use the before/after hooks if that is simpler for you).

**Comment by jenisys** [comment]
Either solved or no longer important.
