### ISSUE TITLE
How to make logging.info() defined in py file take effect?

### ISSUE THREAD

**Issue by Dagon0577** [behave/behave#798]
When learning behave, I defined a test.feature, a test.py file, and introduced a config.py file.

**test.feature**  

    Feature: test   
        Scenario: test 
            Given import init sql

**test.py**  

    from behave import *
    from config import *

    @Given('import init sql')
    def step_impl(context):
            sql_path = "/test/sqls/select/init"
            log_path = "/test/logs/select.log"
            assert executeSQL(sql_path,log_path) == 1

**config.py**  
  
    import pymysql
    import os
    import logging

    host="172.100.9.2"
    user="root"
    password="123456"
    port=3306

    def executeSQL(sql_path,log_path):
            db = pymysql.connect(host=host,user=user,password=password,port=port)
            cur = db.cursor()
            logging.basicConfig(level=logging.DEBUG,
                            filename=log_path,
                            filemode='a',
                            format='%(asctime)s - %(pathname)s[line:%(lineno)d] - %(levelname)s: %(message)s'
                            )
            logging.info("test begin!")
            ......        
            db.commit()
            db.close()
            logging.info('test end!')
            return 1

I use this on the command line and it runs successfully.  

    behave test.feature
But I found that "/test/logs/select.log" does not exist. How can I solve this problem?

**Comment by jenisys** [comment]
Python's `logging` module is a special case.
Plainly said, only one can setup the logging subsystem (once), the main program.
All others only use the logging subsystem (to log some records).
Therefore, you can call `logging.basicConfig()` only once. Then the logging subsystem is setup.
If you call it the second (and ...) time, nothing happens. Basically the setup is ignored because the logging subsystem is already set up.

Because you run under control of `behave`, `behave` configures the logging subsystem. `Behave` supports that the user adapt the logging configuration to its needs. Look in the documentation and `features/logging.*.features`.

SEE ALSO:
* [features/logging.setup_with_configfile.feature](https://github.com/behave/behave/blob/master/features/logging.setup_with_configfile.feature)
