### ISSUE TITLE
Exit status codes

### ISSUE THREAD

**Issue by martingbrown** [behave/behave#801]
In bash it is common to check if an executable has succeded or failed by checking the $? variable, powershell uses $LASTEXITCODE, windows command line has %ErrorLevel%.

Does behave set the Exit Status in any predicatble way so that a script can tell if a test run has failed?

If it does, some explanation of that might be helpful on this page:

https://behave.readthedocs.io/en/latest/behave.html#command-line-arguments

**Comment by jenisys** [comment]
Passing a non-zero exit code back to the user / caller is the normal procedure with any program that I know. Therefore, `behave` uses this behaviour (as expected, at least for me).

CONVENTION:
ZERO (0) = SUCCESS (no problems occurred)
NON-ZERO means a failure or error has occurred 
(failure means some tests failed, error means something unexpected has occured).

Browse the source code if you interested in the internal conventions.
Normally, you get a textual message that describes you what the problem was (or an exception traceback).
