### ISSUE TITLE
How to change the status of a scenario in behave python

### ISSUE THREAD

**Issue by babu1998** [behave/behave#816]
```
def after_scenario(context, scenario):

if scenario.status == Status.failed and context.status == "negative":

    scenario.status = Status.passed

if scenario.status == Status.passed and context.status == "negative":

    scenario.status = Status.failed


```

I am getting HOOK-ERROR in after_scenario: AttributeError: can't set attribute

**Comment by babu1998** [comment]
I haved solved the problem by using scenario.set_status(Status.passed)

**Comment by jenisys** [comment]
Scenario.status is a READ-ONLY property (getter function). Therefore, you cannot assign to it.
Normally, you should not assign/change the status. This is a responsibility of the TestRunner. One way to to it: Use `assert False, „FORCE-FAIL-SCENARIO“` or `raise AssertionError(„FORCE-FAIL-SCENARIO“)` in the Scenario. Or use `scenario.set_status(Status.failed)` etc.

NOTE:
What you are trying to do is BAD-PRACTICE, as far as I understand it from your example. Instead of fixing your tests or potentially flaky tests, etc. you want to falsify the test result.
