### ISSUE TITLE
run steps before everything

### ISSUE THREAD

**Issue by EnricoSemrau** [behave/behave#821]
Hey people, hope you are all healthy and safe during those times.
Is there a way to run some steps/functions in before_all hook.

I was able to to it in before_feature which works just great by using execute_steps function,
and I was wondering if there is a similar solution to run steps before all.

Background is, that we have some steps which are repetitive on some feature files and I only want to run them once before all features, to kinda prepare the environment ad not have to run them over and over again.

Thanks for your help and let me know if you have questions.

**Comment by jenisys** [comment]
If have not really tried it but it should be possible in principle.
Note that:

* the `before_all` hook is somewhat special because you should be able to setup the logging yourself if needed
* the capture mechanism is prepared but not active/started yet
* you should probably use the fixture mechanism with `use_fixture(...)`. Within the fixture implementation you can use `context.execute_steps("""...""")` to execute the steps and have also a cleanup part if needed.
* Using `use_fixture()` in the `before_all` hook ensures that the fixture is only executed once and the attributes in the context remain there until the end. Note that feature/scenario, etc. can override the context-attributes but after execution of the feature/scenario the original attribute values will appear again through the context-layering mechanism.

REASONS WHY I DO NOT NEED THAT (normally):
My step implementations normally have/use a Python API to interact with the SUT/AUT/MUT...
Therefore, I can use this API by calling it directly without using steps, often with similar ease.
