### ISSUE TITLE
Support for shared steps

### ISSUE THREAD

**Issue by athityakumar** [behave/behave#825]
Let's say we have 2 features that have shared step functionality and we'd like to have it as DRY (Don't Repeat Yourself) as possible. Would it be possible to have shared steps?

This setup currently gives **`behave.step_registry.AmbiguousStep: @when('generic starting condition') has already been defined in existing step @when('generic starting condition') at features/steps/shared_steps.py:2`**:

```feature
#! features/foo.feature
Feature: feature foo
  Scenario: scenario 1
    Given generic starting condition
    When condition_1
    Then take action_1

#! features/bar.feature
Feature: feature bar
  Scenario: scenario 1
    Given generic starting condition
    When condition_1
    Then take action_1
```

```py
#! features/steps/shared_steps.py
from behave import given, when, then, step
@given("generic starting condition")
def step_impl(context):
    # do some step which is shared between multiple features

#! features/steps/foo_step.py
from behave import given, when, then, step
from features.steps.shared_steps import *

... #! everything except for: "Given generic starting condition"

#! features/steps/bar_step.py
from behave import given, when, then, step
from features.steps.shared_steps import *

... #! everything except for: "Given generic starting condition"
```

**Comment by xrg** [comment]
Already implemented "macros" in 'behave_manners'. This is an add-on to behave, avoiding to touch the stale project there.
https://github.com/xrg/behave_manners/commit/8e1fd3002eb482dd5564a56ba7efba52fa60c5fe
In short: with a Macro, you can call a group of steps into a single one (step). Then call it at any time.

**Comment by jenisys** [comment]
@athityakumar 
First, get terminology and facts right:

* a step implementation can be used in several features
* two step implementations for the same step (text) in Gherkin are ambiguous (problem: which of the two steps should be executed)
* steps are not specific for one feature

Therefore, you are not talking about shared steps but different implementations for the same step as far as I understand. Another misconception is that "foo_step.py" and "bar_step.py" need to import the "shared_step.py". Why is that needed? The shared steps are already available.

Therefore, you are getting an error, because you are doing something wrong and the exception points you where the problem is.

**Comment by athityakumar** [comment]
Yup, my bad - I'm able to work with it directly 👍
