### ISSUE TITLE
Behave step disambiguation/optional step arguments

### ISSUE THREAD

**Issue by leonardopsantos** [behave/behave#873]
I'm trying to support the following feature scenario:

```
Feature: test
  Scenario: Test optional
      Given attacked by samurai
        And attacked by samurai from behind
```

My steps file is

    from behave import step

    @step('attacked by {opponent}')
    def step_attacked_by(context, opponent):
        print(opponent)

    @step('attacked by {opponent} from {direction}')
    def step_attacked_by(context, opponent, direction):
        print(opponent)
        print(direction)

I'm getting the error:

```
behave.step_registry.AmbiguousStep: @step('attacked by {opponent} from {direction}') has already been defined in
  existing step @step('attacked by {opponent}') at steps/test.py:5
```

I then tried to use [optinal arguments](https://jenisys.github.io/behave.example/step_matcher/use_optional_part.html):

My feature file:

```
Feature: test
  Scenario: Test optional
      Given attacked by a samurai
```

My steps file:

```py
import parse

from behave import step, register_type

@parse.with_pattern(r"a\s+")
def parse_word_a(text):
    """Type converter for "a " (followed by one/more spaces)."""
    return text.strip()

register_type(a_=parse_word_a)

@step('attacked by {:a_?}{opponent}')
def step_attacked_by(context, a_, opponent):
    print(a_)
    print(opponent)
```

And I'm getting this error:

```
    raise ValueError('format spec %r not recognised' % type)
ValueError: format spec 'a_?' not recognised
```

I don't think I really need an optional argument as long as I can disambiguate the steps in the first example.

**Comment by jenisys** [comment]
First, independent which matcher you use, regular expressions are used under the hoods.
And, regular expressions are normally greedy. This means, a regular expression matches as much as possible.
Therefore, your first step placeholder `{opponent}` matches multiple words.

EASY REMEDIES:
* Use more concise, typed placeholders to state your intentions, like: `{opponent:w}` (that matches only one word)
* Use double-quotes to encapsulate placeholders, like: 
  `@step('attacked by "{opponent}"')` and `@step('attacked by "{opponent}" from "{direction}"')`
* Ordering matters: Put longest step(-text)s in front instead of shortest step
  (due to greedy regular expressions and step-registration order is step-search order)

OTHERWISE:
* Use `use_step_matcher("cfparse")` (parse with cardinality-field support), default is: `use_step_matcher("cfparse")`
* Put the default step-matcher into the "environment.py" file via `use_step_matcher("cfparse")`.
  Each loaded step-module will fall-back to this step-matcher. Therefore, it is all in your control.

**Comment by jenisys** [comment]
Have a look at [features/step.duplicated_step.feature:80](https://github.com/behave/behave/blob/master/features/step.duplicated_step.feature#L80) (third scenario).
Could be that the same-step-function detection was not yet present in your older version of behave.
Run the third scenario with your behave implementation to verify that it fails or works for you (works with current behave implementation) and that you observe the same failure syndrome.
Compare [StepRegistry::add_step_definition()](https://github.com/behave/behave/blob/master/behave/step_registry.py#L48) from current master HEAD with the one you are currently using.

MAY BE RELATED:
* [issue.features/issue0171.feature](https://github.com/behave/behave/blob/master/issue.features/issue0171.feature) (solved 6 years ago)
