### ISSUE TITLE
Get tags as user data during run time as opposed to defining a new variable

### ISSUE THREAD

**Issue by mathew-jithin** [behave/behave#879]
Is there any way we can directly get the tags passed in CLI during runtime, rather than defining a new variable and passing it up as user defined data?

Basically, is the one defined here the only way to achieve the same?

https://stackoverflow.com/questions/46655493/how-can-i-get-current-set-of-tags-passed-from-behave-command

@jenisys Hope you will please help here.

**Comment by jenisys** [comment]
I am slightly confused:

* **userdata** is used for providing data to the user, normally used within the test run.

* **tags** are used as markers/labels in Gherkin. The main purpose is to reference select/exclude the model elements (features, scenarios, rules, ...) during the test run. But other usecases exist: active-tags, fixture-tags, ...

* **active-tags**: A special variant of tags, where the tag describes a condition „<name> == <value>“. The value is normally queried from the system-under-test (SUT) or you can provide the value as userdata. This mechanism is needed to provide a skip-if logic that automatically skips tests because you know that the test will fail because its preconditions/assumptions are not met.

* **tag-expression**: On the command line (or in the config-file) you actually do not provide tags. Instead you provide a tag-expression, a Boolean expressions, that allow the test runner to select which model elements should be executed during the test run (and which are skipped/excluded during the test run).

Now tell me what you are trying to do (and provide a concrete, simple example).

SEE ALSO:

* [tag-expressions-v2](https://behave.readthedocs.io/en/latest/new_and_noteworthy_v1.2.7.html#tag-expressions-v2)
* [active-tags and userdata](https://behave.readthedocs.io/en/latest/new_and_noteworthy_v1.2.6.html?highlight=Userdata#tagged-examples-with-active-tags-and-userdata)
* [userdata](https://behave.readthedocs.io/en/latest/new_and_noteworthy_v1.2.5.html?highlight=Userdata#index-7)

NOTE:
* behave-1.2.6 and before uses the old tag-expression mechanism (tag-expressions v1).
* behave-1.2.7 and newer uses the new cucumber-tag-expression mechanism (tag-expression v2), which is more readable and flexible and you better unterstand what you are doing. Backward compatibility to tag-expressions v1 is currently automatically be discovered (but: tag-expression v1 will become deprecated in the future).

**Comment by jenisys** [comment]
CLOSE ISSUE: No additional information was provided (to clarify the issue).

**Comment by jenisys** [comment]
HINT: Try `ctx.config.tags` or `ctx.config.tag_expression`(repo HEAD) to access the tags/tag-expression that is passed on command-line (or from config-file if none are provided on command-line).
