### ISSUE TITLE
How to get a list of all implemented steps?

### ISSUE THREAD

**Issue by berndhahnebach** [behave/behave#886]
see question? Is this possible somehow?

If I use --steps-catalog it asks for a feature file. But I would like to get a list of ALL implemented steps.

```
$ behave --steps-catalog
ConfigError: No feature files in '/home/hugo/.FreeCAD/Mod/bimtester/code_bimtester/bimtester/features'
$
```

**Comment by bittner** [comment]
The error message suggests that you have no `feature` directory. Inside there `behave` wants to look for a `steps` directory. Do you have a working setup of Behave? If you have try to specify it as an argument for `behave`. If not, take a look at the [tutorial](https://behave.readthedocs.io/en/latest/tutorial.html#features) first, please.

Otherwise, you may want to take a look at the existing steps formatters, e.g.
```console
$ behave -f help
Available formatters:
  ...
  steps          Shows step definitions (step implementations).
  steps.catalog  Shows non-technical documentation for step definitions.
  steps.doc      Shows documentation for step definitions.
  steps.usage    Shows how step definitions are used by steps.
  ...
```

Note that, according to `behave --help`, the `--steps-catalog` is really just a shortcut for one of those formatters:

```console
  --steps-catalog       Show a catalog of all available step definitions. SAME
                        AS: --format=steps.catalog --dry-run --no-summary -q
```

**Comment by berndhahnebach** [comment]
Yes I have set up behave with dozens of implemented steps. Thus I would like to have a overview what steps are available.

**Comment by bittner** [comment]
Did you manage to fix the error? You should do that first.

Then try whether one of the formatters [mentioned above](https://github.com/behave/behave/issues/886#issuecomment-748261043) satisfy your needs. If not, please specify in detail

1. what output you get (which matches your expectations most closely) and which command you used to generate it
1. what the output should look like that you expect (please give a concrete example)

**Comment by berndhahnebach** [comment]
But I would like to have a list of all available steps, independent from my feature files. Just all available steps.

**Comment by berndhahnebach** [comment]
> The error message suggests that you have no `feature` directory. Inside there `behave` wants to look for a `steps` directory. 



```
$ ls -l  features/steps/
insgesamt 96
--rw-r--r-- 1 hugo hugo 2786 Dez 16 21:57 classification.py
-rw-r--r-- 1 hugo hugo 3092 Dez 16 21:57 geocoding.py
-rw-r--r-- 1 hugo hugo 9409 Dez 16 21:57 geolocation.py
...
```


```
$ cat features/steps/classification.py
import json
from behave import step

from utils import assert_attribute
from utils import assert_type
from utils import IfcFile


def get_classification(name):
    classifications = [c for c in IfcFile.get().by_type("IfcClassification") if c.Name == name]
    if len(classifications) != 1:
        assert False, f'The classification "{name}" was not found'
    return classifications[0]


@step("The classification {name} must be used")
def step_impl(context, name):
    get_classification(name)


@step("The classification {name} is published by {source}")
def step_impl(context, name, source):
    assert_attribute(get_classification(name), "Source", source)
```

and many more python modules with many more steps. I wuold like to get a list of all steps which are implemented.
```

**Comment by berndhahnebach** [comment]
```
$ behave --steps-catalog
ConfigError: No feature files in '/home/hugo/.FreeCAD/Mod/bimtester/code_bimtester/bimtester/features'
```

behave wold like to have feature files ...

**Comment by berndhahnebach** [comment]
damn I got it  ...

inside the directory features one needs to create an empty file `some_fancy_name.feature ` than the command works and all steps are printed.

I may should have mentioned I do not have all my feature file inside this directory. We use behave in a slightly different context. The feature files do change quite often.

**Comment by berndhahnebach** [comment]
may be interesting in this regard. https://github.com/behave/behave/issues/871 See the last two posts ...

**Comment by berndhahnebach** [comment]
Feature request:
make it possible without this dummy feature file

**Comment by jenisys** [comment]
> damn I got it ...
> 
> inside the directory features one needs to create an empty file `some_fancy_name.feature ` than the command works and all steps are printed.
> 
> I may should have mentioned I do not have all my feature file inside this directory. We use behave in a slightly different context. The feature files do change quite often.

Mmh, if the feature files change very often, I would consider it a "SMELL", meaning you are probably doing something wrong.
If you feature files change, your function and/or the behaviour of your functionality changes. That is rather BAD, especially if it changes often. If you only add additional scenarios or slightly modify existing ones that may be OK. But otherwise, you are in big trouble (from my point of view) because the feature files are your test suite and safety to ensure that everything still works if you are making changes to the source code.

OTHERWISE:
`behave` can not perform mind-reading. Therefore, it performs the normal checks to discover the `steps/` directory.
If you have no feature files in your feature directory that is (at least for me) a rather weird case. And in your case, you have stumbled over it. An empty feature file is sufficient in your case (as you have discovered yourself).

**Comment by berndhahnebach** [comment]
As I said we use behave in a slightly different context to tes BIM models. The test change due to the requirement on the BIM model. ATM we have a set of around 50 tests and choose what we need if we test a model. The needed feature files will be generated or manually edited an copied before the test run.

**Comment by berndhahnebach** [comment]
BIM https://de.m.wikipedia.org/wiki/Building_Information_Modeling
