### ISSUE TITLE
Scenario Outline: Avoid to rerun some costly step(s) for each Example

### ISSUE THREAD

**Issue by davidwneary** [behave/behave#922]
Hi guys, thanks for the great product!

I want to be able to do something like this. The following is a bit of a contrived example from a JIRA-like site where you can view stats on a dashboard that should filter their numbers based on the users that are selected.

```gherkin
Given the team project exists
And the user is viewing the dashboard
And the following <users> are selected
Then stat box <stat_name> will show <value>
| users          | stat_name                       | value       |
| bob,andy       | tickets_in_progress             | 1           | 
| sally          | velocity                        | 5           | 
```

So I essentially want the last to lines to be repeated for each row in the table.

Obviously this is very similar to a ScenarioOutline with Examples but in my case `Given the team project exists` is actually several more steps and relatively time consuming and the number of entries in the table is quite large so I don't want to repeat the earlier steps for each row. 

Is there a way to do this at the moment and/or is this functionality you would consider adding?

Thanks for your time!

**Comment by jenisys** [comment]
If you specify a step in Gherkin, the step is executed during the test run. You cannot avoid that.
**BUT:** You can solve the problem in your step implementation (under the hoods; as step implementation detail):

* You basically use the **use-or-create-resource** style (or memorize last / caching)
* If the resource is already created (and configured correctly), just reuse the existing resource
* If the resource does not exist, you need to create it w/ the supplied configuration

```python
# — FILE: features/steps/some_steps.py
from behave import given
from behave4my_system import the_resource_manager

@given(‘the user is viewing the dashboard‘)
 def step_given_the_dashboard(ctx):
      ctx.dashboard_page = the_resource_manager.use_or_create_dashboard_page()
```

NOTE:
A similar functionality was requested for Gherkin (in the cucumber repository) for „FeatureBackground“ (or something similar). Its steps should only be executed once instead of executing the Background steps for each Scenario. Such a functionality was rejected at that time.
