### ISSUE TITLE
Steps's name cannot start with the same prefix when they use parameters.

### ISSUE THREAD

**Issue by rdebroiz** [behave/behave#924]
Using behave 1.2.6, and given the steps definition:

```python
from behave import *
from behave.runner import Context


@then('foo is foo')
def foo(context: Context):
    assert "foo" == "foo"


@then('foo is "{foo}"')
def foo_is_foo(context: Context, foo: str):
    assert foo == "foo"


@then('foo is "{foo}" if bar is "{bar}"')
def foo_is_foo_if_bar_is_bar(context: Context, foo: str, bar: str):
    if bar == "bar":
        assert foo == "foo"
```
and the features:
```gherkin
Feature: my feature
  Scenario: my scenario
    Then foo is foo
    And foo is "foo"
    And foo is "foo" if bar is "bar"
```
The parser complains
```
behave.step_registry.AmbiguousStep: @then('foo is "{foo}" if bar is "{bar}"') has already been defined in
  existing step @then('foo is "{foo}"') at features/steps/foo.py:10
```
What I would expect:
both steps function to be registerd, `'foo is "{foo}"'` being different from `'foo is "{foo}" if bar is "{bar}"'`

**Comment by jenisys** [comment]
This is an ordering problem and has to do with greedy regular expressions (in match-anything placeholders).
This can currently be solved (by you) with two approaches:

* ORDERING: Put step with longest step name/pattern first (or before the other one that causes the problem)
* Use types on placeholders (without it: The second step definition basically matches anything and therefore conflicts with the last step definition)

```python
# HERE: Placeholders may contain one word
@then(‘foo is “{foo:w}“‘)
…

@then(‘foo is “{foo:w}“ if bar is “{bar}“‘)
…
```

NOTE: The parser does not complain. It is the test runner that tries to load and register the step definitions.
This error message has a reason. Otherwise, the second step definition will be executed while you think/expect that the third one would be used.

**Comment by rdebroiz** [comment]
Thanks for your detailed explanation @jenisys. It would be more user friendly if the regular expression could be fixed though :)

**Comment by UncleGoogle** [comment]
Confirm that is a problem between different scenarios and features as well. Workaround with ordering implementation function works.
