### ISSUE TITLE
Steps played by execute_steps in before_feature not shown during execution

### ISSUE THREAD

**Issue by rpallier** [behave/behave#931]
Hi,

Using @tags, before_feature and execute_steps() i wanted to play generic configuration validation test for a Feature (not via the Background which is executed for each Scenario).

It's working but do not display a green line for each step passed via execute_steps().

I've seen that capture where not visible on hook so i added a @capture above before_feature and nothing.

Am i using something wrong/ forgot something or is it not possible yet ?

Regards,

**Comment by jenisys** [comment]
`execute_steps()` allows you to provide a macro-like functionality with a step. Therefore, you only get:
* the macro-step result PASSED or 
* the macro-step result FAILED and the sub-step that caused the problem

HINT:
* You normally only get to see the result of the steps that you write in the feature file
* In cases of failure, you see the fault location

**Comment by rpallier** [comment]
Hi,

Ok, is there a behave print function to make it possible like this (or another functions, function, way through try/except/finally)) ?

```
def execute_steps_printed(steps: List[str]):
    for step in steps:
        print_step_grey(step)
        try:
            step_passed = execute_steps(step)
        except: Exception as e:
            step_passed = false
            #handle e
            #raise e or another exception
        finally:
            print_step_green_or_red(step, step_passed)
```

**Comment by jenisys** [comment]
No, the thing you are looking for is called **Scenario** (using the Pretty-Formatter).
No, such a thing is not provided, because there is no common use case for this.

But you are trying to solve two different things:

* Providing your own `executed_steps()` implementation (what you can)
* Providing your own Formatter that shows the low-level details (will mess up the Formatter output)

**BE AWARE:** `execute_steps(steps)` can contain steps that need `execute_steps()` (RECURSIVE USE)
**HINT:** If you are just curious about the low-level details, provide an own `execute_steps()` function that logs the processing details (instead of using print that messes up the primary output) and logging is redirected to a file (for later inspection). As alternative, use logging statements in your step implementations.

**QUESTION:** Why do you want to see all this low-level details?

**Comment by rpallier** [comment]
> BE AWARE: execute_steps(steps) can contain steps that need execute_steps() (RECURSIVE USE)

Good point. We must be careful.

> HINT: If you are just curious about the low-level details, [..] use logging statements in your step implementations.

Maybe we'll do that if the print mess up the Formatter output

> QUESTION: Why do you want to see all this low-level details?

Without print during the before_feature, some executions have no output during long time before the first Scenario's step begins, it can be disturbing.

The goal here is to use steps to initialize Feature's configuration.
Each Feature have its own configuration so using tags at the Feature definition level helps in specifying it.
The persons whom will write the Features need the configuration part to be visible in the execution output.

**Comment by jenisys** [comment]
Mmh, the underlying problem seems to be that your „fixture“ setup takes a larger amount of time. And this problem by itself is independent how this setup is performed:
* By calling a function (or a sequence of functions)
* By using execute_steps()

If you compare that with pytest: The fixture setup also goes unnoticed; you will not see it in the test progress.
* Use print statements either in your execute_steps method (or hand over a behave Formatter)
* Use logging as low-level diagnostics (where you can peek and see if your making progress)
* Use some kind of feedback device that blinks or changes color when a step is started/finished

My preferred solution in this case would be the logging (as secondary output).
Otherwise, I would try to reduce or avoid the larger setup times (if that is feasible for you).
