### ISSUE TITLE
pyproject.toml (PEP 518) support

### ISSUE THREAD

**Issue by pauloxnet** [behave/behave#944]
Hi! Is there a plan to support `pyproject.toml` from [PEP 518](https://www.python.org/dev/peps/pep-0518/)?

Specifically, it would be nice if `behave` could understand `[tool.behave]` section in the `pyproject.toml` file like other python libraries do (e.g. `black`, `coverage`, `isort`, `mypy`, `pytest`, ...)

**Comment by bittner** [comment]
No plans, but if that's important for you and it helps us to follow a popular trend, why not add it?

Do you want to prepare a PR for that? Search for, [e.g. setup.cfg](https://github.com/behave/behave/search?q=setup.cfg), to find the places that potentially need to be adapted.

**Comment by pwoolvett** [comment]
I'd like to take a shot at it. Some questions @bittner :

* how do you want to handle toml not being in the stdlib?
  1. add as optional extra dependency
  2. use configparser directly for `pyproject.toml` (!) instead of a proper toml lib (hacky, but could be done)
* [Here](https://github.com/behave/behave/blob/bfda54448906d919ffd3fa4424b6d3c155a5388b/behave/configuration.py#L404), is the `use_raw_value` used just to avoid crashes because of the `%`s in the `logging_format` options?  In other words, is string interpolation required and expected for other values not in raw_value_options? This is specially important if we're using a proper toml library.
* In which position of the configfiles should `pyproject.toml` be read? I assume after `.behaverc` and `behave.ini`, but what about `tox.ini` asnd `setup.cfg`?
* Given that now some parsing is going to be required, are you for or against using a class-based approach? eg `Reader.read_raw_opts`(https://github.com/behave/behave/blob/bfda54448906d919ffd3fa4424b6d3c155a5388b/behave/configuration.py#L388-L414), `Reader.format_outfiles_coupling`(https://github.com/behave/behave/blob/bfda54448906d919ffd3fa4424b6d3c155a5388b/behave/configuration.py#L417-L431), `Reader.parse_paths`(https://github.com/behave/behave/blob/bfda54448906d919ffd3fa4424b6d3c155a5388b/behave/configuration.py#L433-L439), and `Reader.parse_extra`(https://github.com/behave/behave/blob/bfda54448906d919ffd3fa4424b6d3c155a5388b/behave/configuration.py#L443-L450)?

  The alternative is copy-pasting the [read_configuration](https://github.com/behave/behave/blob/bfda54448906d919ffd3fa4424b6d3c155a5388b/behave/configuration.py#L381) replacing with the parsing wher appropiate.
  
  
  Also, I'm assuming the proper location would be `tool.behave` and `tool.behave.formatters`, etc, because of [pep 518](https://www.python.org/dev/peps/pep-0518/#tool-table)

**Comment by bar** [comment]
@pwoolvett I bet you didn't want to at handle me, right?

**Comment by bittner** [comment]
Wow, this is surprising! I would have expected adding support for another (ini-style) configuration file a straight-forward task. :worried: 

For all questions above, I'd say:

1. Use common sense
1. Take a look at how other projects handle the issues
1. Pick the most elegant and small-footprint solution

**Comment by pauloxnet** [comment]
> @pauloxnet are you on it already? If not,  I'd like to take a shot at it.

I'm not working on it. You're free to open a PR.

**Comment by bittner** [comment]
Re @pwoolvett:

> How do you want to handle toml not being in the stdlib?

I would suggest to add an [extra dependency](https://setuptools.pypa.io/en/latest/userguide/dependency_management.html#optional-dependencies), so that future users must install `behave[toml]` in order for `pyproject.toml` configuration support to be activated. This way, no additional packages are installed if you don't opt in for `pyproject.toml` support.

For reference, [Coverage.py does it that way](https://coverage.readthedocs.io/en/latest/config.html) already. 

> In which position of the configfiles should `pyproject.toml` be read?

I would give it the lowest precedence, because it has been added last. Unless there is a good reason not to do so.

**Comment by pwoolvett** [comment]
Current PR #991 .


> 1. How do you want to handle toml not being in the stdlib?

Added as optional extra dependency

>     2. [Here](https://github.com/behave/behave/blob/bfda54448906d919ffd3fa4424b6d3c155a5388b/behave/configuration.py#L404), is the `use_raw_value` used just to avoid crashes because of the `%`s in the `logging_format` options?  In other words, is string interpolation required and expected for other values not in `raw_value_options`? This is specially important if we're using a proper toml library.

There's no interpolation in `toml`, so there's a warning added in the docs.

>     3. In which position of the configfiles should `pyproject.toml` be read? I assume after `.behaverc` and `behave.ini`, but what about `tox.ini` asnd `setup.cfg`?

Added in last position

>     4. Given that now some parsing is going to be required, are you for or against using a class-based approach? eg
>        [`Reader.read_raw_opts`](https://github.com/behave/behave/blob/bfda54448906d919ffd3fa4424b6d3c155a5388b/behave/configuration.py#L388-L414),
>        [`Reader.format_outfiles_coupling`](https://github.com/behave/behave/blob/bfda54448906d919ffd3fa4424b6d3c155a5388b/behave/configuration.py#L417-L431),
>        [`Reader.parse_paths`](https://github.com/behave/behave/blob/bfda54448906d919ffd3fa4424b6d3c155a5388b/behave/configuration.py#L433-L439),
>        and [`Reader.parse_extra`](https://github.com/behave/behave/blob/bfda54448906d919ffd3fa4424b6d3c155a5388b/behave/configuration.py#L443-L450)?

No refactor performed in order to minimize impact for the moment. Its (subjectively) uglier and (not that subjectively) less maintainable/debbugable than the proposed class-based approach, though.

>     5. How would you translate the following? The "`(@foo or not @bar) and @zap`" in the docs

 ```toml
#pyproject.toml
[tool.behave]
...
default_tags = ["@foo,~@bar", "@zap"]
```

> BTW, I'm assuming the proper location would be `tool.behave` and `tool.behave.formatters`, etc, because of [pep 518](https://www.python.org/dev/peps/pep-0518/#tool-table)

Added to docs
