### ISSUE TITLE
Delayed step execution and scenario result without holding testing.

### ISSUE THREAD

**Issue by govindasharma1986** [behave/behave#951]
Lets consider a scenario:

I have a feature file in which there are 5 scenarios. Each scenario has 10 steps. The last 4 steps are `Then` steps. The last step i.e. 10th step needs me to verify something in a table after `x` mins. For each scenario, the waiting duration for 10th step could be varying and this would be known beforehand.
For example: scenario1:step10 the wait is 10mins, for scenario2:step10 the wait is 16 mins and for scenario3:step10 the wait is 22 mins and so on...

Now, to implement it I tried:
1. `time.sleep(duration)`
    1. The problem with this approach is that it halts testing.

2. I changed all my steps to async - await.
    1. There is no difference(it's synchronous). I expected that it would execute next scenario because of async behaviour.
```
@behave.then('Execute some step after "{duration}"')
@behave.api.async_step.async_run_until_complete()
async def step_impl(context, duration):
    await asyncio.sleep(duration)
    actual = check_something_in_db()
    assert actual==True
```

3. Thought of using parallel tests but behave does not officially support this yet.

4. Thought of using RabbitMQ with Celery and scheduling `step10` of each scenario  but behave would have assigned all scenarios a status: (Pass/Fail). So if Scenario1 was marked as Pass and after 10 mins when Step10 executes and it fails then I would not be able to update status of Scenario1 in behave.

I think maybe **parallel tests execution** along with support for **delayed step execution** and **delayed test/scenario results** would be very helpful.

I don't know how clearly I have explained my problem but incase my words are confusing please let me know I will try to elaborate further.

**Comment by jenisys** [comment]
No, its not.

Each step needs a its result before the next step is executed. Normally, if a step fails the remaining steps are skipped because the scenario has already failed.

Only because you have slow tests, you want to change the test runner constraints, basically the test runner protocol. Be creative and make your tests fast instead of fighting the test runner protocol.

Even if you use parallel execution, each scenario will be executed in a sequence of steps (sequentially). You basically just run multiple scenarios in parallel. And this opens another can of worms if you have shared resources between scenarios.

STEP DESIGN HINTS:
* How you design your steps is up to you. Therefore, you can move some verification parts towards the back of the scenario. But that makes the steps where you skip the actually work to a later time often less useful.
* You can trigger the start of the execution of an async task in a step, store the future in the context and collect/verify the result in a later step (or wait until the task is finished).

NOTES:
* Try to use an event-based approach instead of wait-based approach. In general, this leads to less unnecessary wait-and-check durations.

**Comment by govindasharma1986** [comment]
The problem is that, there is a pipeline worker(message queue) which executes a job after 20mins to insert something in db table. I have no control over the app I am testing.

These are compliance test so I cannot ignore them. Also the API is tightly coupled with frontend cookies, so need to test E2E using selenium.

I would really appreciate if you could consider it.

**Comment by kevwilde** [comment]
Hi @govindasharma1986 best is to split those tests up by having one test check if  the message is added to the queue
and then follow up with a brand new test where you verify that the specific message actually gets processed correctly by the queue workers. This is the approach we use to create fast tests.

**Comment by govindasharma1986** [comment]
Thankyou very much! I will talk with dev team for an endpoint to read message queue. Thanks again ;)
