### ISSUE TITLE
Playwright browser automation support

### ISSUE THREAD

**Issue by nasmal** [behave/behave#971]
[Playwright](https://playwright.dev) is a very popular package to end-to-end test web apps. Just curious if adding Playwright support into Behave would be a good fit for the project. Has this been considered before?

**Comment by jenisys** [comment]
In my opinion, it is not a good idea to integrate `Playwright` directly into `behave`.
Otherwise, people that do not want to use `Playwright` will need to "pay for it" (increased package size).

**BETTER IS:**
* Provide an example that shows how to use `Playwright` it (or a blog entry that describes it)
* Provide an behave extension, for example named like `behave4playwright`, that contains helper(s) and utilities for other that want to use `Playwright` with `behave` (if such additional functionality is needed and useful for others)
  
HINT:
This extension could be provided under: https://github.com/behave-contrib
(which simplifies it for others to find it)

**Comment by zp4rand0miz31** [comment]
Merging both API tests and Web UI tests in the same BDD scenario... Isn't that the goal of a BDD framework ?

**Comment by jenisys** [comment]
@zp4rand0miz31 
Nope.

Behave provides a generic solution that is independent of the problem domain.
Web UIs are an own problem domain, API testing is actually another problem domain.
And there are many different other problem domains out there.

You are better served if you provide a concrete solution for testing Web UIs with a framework like Playright by providing a step-library for this with `behave`. The same is true if you want to use Selenium with `behave` instead.

Therefore, provide one if you are interested.
It is not difficult. If you use your head, everything is possible.
